### ISSUE TITLE
Add support for MTOM message encoding

### ISSUE THREAD

**Issue by osalas891123** [CoreWCF/CoreWCF#10]
Want to configure a custom binding SOAP 1.2 with MTOM support. Is this possible

**Comment by mconnew** [comment]
It will support CustomBindings but the channel layer api shape is changing. If you only use built in binding elements then you won't need to worry about it. If you have your own custom channel layer, then you will need to modify your code.  
MTOM support won't be in the initial release. It's definitely something which can come later but it's not been planned for yet.

**Comment by szyb** [comment]
Two years have passed since your reply. Has anything changed in the priorities for MTOM support?  In the voting thread "Feature Roadmap Vote" (https://github.com/CoreWCF/CoreWCF/issues/234) it's pretty high (2nd place as for now).

**Comment by osalas891123** [comment]
Nothing has changed and this is one of the more used features (Healthcare Domain, a lot of projects)

**Comment by mconnew** [comment]
I have recently ported Mtom support for the WCF Core client (at https://github.com/dotnet/wcf) so I should be able to port it here easily enough. Expect it soon (like in the next few months). If anyone want to bring it over to get it in CoreWCF sooner, I can point you to the commit which contained it and help answer any questions. It shouldn't be a lot of changes needed to bring it over.

**Comment by mconnew** [comment]
Here's the steps that need to happen to port MTOM. The diff which contains all the code for the client is [here](https://github.com/dotnet/wcf/commit/3856a2e6ae0dfe9ea4f32493e7a9d46a42d11252).
1. Copy the following files to the primitives project changing namespace where needed:
  * src/System.Private.ServiceModel/src/Internals/System/Text/BinHexEncoding.cs
  * src/System.Private.ServiceModel/src/Internals/System/Xml/XmlConverter.cs
  * src/System.Private.ServiceModel/src/Internals/System/Xml/XmlExceptionHelper.cs
  * src/System.Private.ServiceModel/src/Internals/System/Xml/XmlMtomReader.cs
  * src/System.Private.ServiceModel/src/Internals/System/Xml/XmlMtomWriter.cs
  * src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MtomMessageEncoder.cs
  * src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MtomMessageEncodingBindingElement.cs
  * src/System.Private.ServiceModel/src/System/ServiceModel/WSMessageEncoding.cs - Might need to be copied or updated, but might be fine
2. Copy new string resources from the diff across to the primitives strings.resx  
3. Update the following binding classes  
    1. BasicHttpBinding.cs
        * Add MessageEncoding property
        * Update CreateBindingElements to use MtomEncodingBindingElement  
    2. HttpBindingBase.cs
        * Add MtomMessageEncodingBindingElement internal property and add code referencing it  
    3. NetHttpBinding.cs
        * Update CreateBindingElements to use MtomEncodingBindingElement  
    4. WSHttpBindingBase.cs 
        * Add MtomMessageEncodingBindingElement field and code which references it
        * Add MessageEncoding property
        * Update Initialize method to create MtomMessageEncodingBindingElement and apply message version
        * Update CreateBindingElements to use the Mtom message encoder  
    5. MessageEncoder.cs
        * You might need to update this to add GetTraceSourceString, but probably not as that's used for tracing and we currently comment all that code out
4. Add tests. You should be able to modify an existing test for the bindings by switching to use `[Theory]` instead of `[Fact]` and using `[InlineData]` to have variants based on the message encoding being used. Take a look [here](https://github.com/dotnet/wcf/blob/3856a2e6ae0dfe9ea4f32493e7a9d46a42d11252/src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/NetHttpBindingTests.4.0.0.cs#L12) and [here](https://github.com/dotnet/wcf/blob/3856a2e6ae0dfe9ea4f32493e7a9d46a42d11252/src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs#L16) to see an example. For specifying for message encoding for client and server, you can cast the CoreWCF enum type to the System.ServiceModel enum type. You won't be able to do the tests without specifying the RC1 version of the System.ServiceModel.* packages as that's when MTOM is first shipping for the WCF core client which should be within a couple of weeks of this comment.

**Comment by g7ed6e** [comment]
Thanks @mconnew for détails. As discussed please assign to me.
