### ISSUE TITLE
IndexOutOfRangeException in DataContractSerializerOperationFormatter

### ISSUE THREAD

**Issue by bzwieratinnovadis** [CoreWCF/CoreWCF#1007]
In our WCF server-side implementation we add custom headers to certain messages by applying an endpoint behavior. See the following gist for the implementation of this behavior: https://gist.github.com/bzwieratinnovadis/fb1ce9ca35355481dfa13ee919711aee

Then we apply the behavior like this:
```csharp
public static void AddFlowService<TServiceContract, THeader>(this IServiceBuilder serviceBuilder,
    string address, Binding? binding = null, bool includeExceptionDetailInFaults = false)
    where TServiceContract : class
{
    serviceBuilder.AddService<TServiceContract>(options =>
    {
        options.DebugBehavior.IncludeExceptionDetailInFaults = includeExceptionDetailInFaults;
    });

    serviceBuilder.AddServiceEndpoint<TServiceContract, TServiceContract>(binding ?? Binding, address,
        endpoint => endpoint.EndpointBehaviors.Add(new AddWsdlHeaderBehavior<THeader>()));
}
```

When calling the endpoints where the behavior is applied we get the following error on the response (the request works fine):

> System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Index was outside the bounds of the array. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CoreWCF.Dispatcher.DataContractSerializerOperationFormatter.AddHeadersToMessage(Message message, MessageDescription messageDescription, Object[] parameters, Boolean isRequest)
   at CoreWCF.Dispatcher.OperationFormatter.SerializeReply(MessageVersion messageVersion, Object[] parameters, Object result)
   at CoreWCF.Dispatcher.DispatchOperationRuntime.SerializeOutputs(MessageRpc rpc)
   at CoreWCF.Dispatcher.DispatchOperationRuntime.InvokeAsync(MessageRpc rpc)
   at CoreWCF.Dispatcher.DispatchOperationRuntime.InvokeAsync(MessageRpc rpc)
   at CoreWCF.Dispatcher.ImmutableDispatchRuntime.ProcessMessageAsync(MessageRpc rpc)
   at CoreWCF.Dispatcher.MessageRpc.ProcessAsync(Boolean isOperationContextSet)).

It seems to be this line specifically: https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Primitives/src/CoreWCF/Dispatcher/DataContractSerializerOperationFormatter.cs#L193

The weird thing is that there is data in the array at the index when I debug the code so I'm not sure why the exception is thrown. It seems to be either a bug in the library or maybe we are adding the headers incorrectly? I'd be really grateful if we can get some help on this because this is the last issue to tackle before going to production with the CoreWCF upgrade.

**Comment by bzwieratinnovadis** [comment]
@mconnew It's been a while since I opened this issue and I would like to know whether it has been at least acknowledged by the team. It's literally the last issue to solve in order to complete our migration to CoreWCF.

Thanks!

**Comment by mconnew** [comment]
I'm sorry, this one slipped through the cracks. This isn't a bug in CoreWCF, this is a misunderstanding on how to achieve the goal you want. Can you explain what it is that you want to achieve and I can help you with how to do that? Long explanation as to what's happening and why follows:

 It's not going to be that line of code, the index is bounded by the length of the array in the for loop, so it can't be out of range. It's [this line](https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Primitives/src/CoreWCF/Dispatcher/DataContractSerializerOperationFormatter.cs#L195) and the problem is the parameters array is smaller than the headerParts array.  
This is caused by a bug in your behavior, most likely caused by a misunderstanding on how to achieve something. Here's what's happening. When you have an operation defined like this:
```
[OperationContext]
string DoWork(int a, string b, double c, out DateTime timestamp);
```
This is converted into an operation description with a list of parts. There's 1 part for every parameter that will be passed to the operation, in this case 3 of them. There's also 1 part for every return parameter. In this case that's 2, one for the return value, and one for the out parameter. The return value is handled separately so the parameters array here only contains the out parameters. When we invoke the operation, we create 2 arrays, one for the input parameters, and one for the output parameters (ref parameters end up being represented in both). The input array is passed to the IDspatchMessageFormatter.DeserializeRequest which deserializes the message and populates the input array. The input and output arrays are passed to the IOperationInvoker which calls the method. Any out parameters from the method get copied into the output array. If your operation has no out (or ref) parameters, the output array is an empty array.  
When it comes to serializing the reply, each of the out parameters which have been defined to be sent as headers (e.g. when using MessageContract to define your operation) will be in the headerParts array. The `headerPart.Description` is of type `MessageHeaderDescription` and this has an `Index` property. That `Index` property says which out parameter it's referring to. So for example, in the example operation above (ignoring that it's not a header part but for the body) would have an index of 0 as there's only 1 out parameter and it's the first one so the array index will be 0.  
What you've done is said is every incoming and outgoing message has a parameter which is to be represented as a MessageHeader. As you aren't setting the Index, it defaults to 0. This means you are saying the first parameter of every incoming request is to be read from a SOAP header, and every response has at least one out parameter and the first one is to be sent as a message header. You also haven't modified any of the existing message description so if an operation does happen to have these traits, it will attempt to deserialize it from the incoming message and from a message header. You basically doubled up a single method parameter to multiple sources. The same on the response, you would serialize the out parameter to the SOAP body AND to a SOAP header.  
The exception is being thrown because you have declared there to be an out parameter to be used for a message header in the response, but the actual .NET method has no out parameters. When it comes time to serialize the reply, it's reading the MessageHeaderDescription index of 0, and trying to reference the first entry in an empty array, which results in a IndexOutOfRangeException.

**Comment by bzwieratinnovadis** [comment]
@mconnew First of all, thank you for taking the time and effort to explain this in so much detail. Now I understand what the issue is but it's not clear to me how to solve it, yet.

What we want to achieve is to add our own SOAP header in both the request and response for specific endpoints, regardless of parameters. So far, the solution I mentioned used to work with the old ServiceModel namespace without having an additional (out) parameter for the header. So I think it's fair to say that the way message serialization works in CoreWCF is different from how it used to be implemented, right? Hence my suspicion this might be a bug in the library.

Here's an example of one of the endpoints we are applying the behavior to:
```csharp
[OperationContract(Action = "SendMessage")]
ShvMessageConfirmation SendMessageAsync(SeMessage bericht);
```

By applying the behavior it will insert the header dynamically rather than having to define it for each endpoint by using a parameter. An alternative could be to use MessageContracts, but unfortunately this will change the WSDL and therefore it's a breaking change for our clients. We are looking for a solution that results in no breaking changes to the WDSL, but so far I have not found a solution.

**Comment by mconnew** [comment]
Some of the code was ported from .NET Framwork, and some from the WCF Client code, so it's possible there's some subtle differences, but I would have expected an exception with your code so I don't know why it's working on .NET Framework.  

As you are adding values as headers, you don't need to do anything to the message description as that's only needed if you want CoreWCF to automatically map the header to an operation parameter. I suspect an IDispatchMessageInspector should be able to do what you need, but I need a bit more information to provide a full answer how you would do this.  

The behavior you provided a link to only adds the header to the description, it doesn't actually provide the value that will be in the header. When receiving a request, how do you currently consume the header value? When sending the reply, how do you provide the value which will be going into the header? Or is it that you just need the header to be present and the content is empty?

**Comment by bzwieratinnovadis** [comment]
Thank you for the detailed explanation! Based on that I managed to figure it out and I got it working correctly.
