### ISSUE TITLE
ActionMessageFilter inaccessible due to its protectionlevel

### ISSUE THREAD

**Issue by RobThree** [CoreWCF/CoreWCF#1042]
It [appears](https://github.com/CoreWCF/CoreWCF/blob/0ebc14d529a2de9b97bc64866b99dc4c0d2922d2/src/CoreWCF.Primitives/src/CoreWCF/Dispatcher/ActionMessageFilter.cs#L13) the `ActionMessageFilter` is internal, but if I'm not mistaken it's 'supposed' to be [public](https://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/Dispatcher/ActionMessageFilter.cs,14). I'm not sure if there's a reason to have made it internal, but I'm trying to get to the [actions](https://github.com/CoreWCF/CoreWCF/blob/0ebc14d529a2de9b97bc64866b99dc4c0d2922d2/src/CoreWCF.Primitives/src/CoreWCF/Dispatcher/ActionMessageFilter.cs#L61) implemented by an endpoint so I can create telemetry counters for each of the implemented operation contracts of a class.

Is this intentional, or is it just a slight oversight and can this class be made public?

**Comment by mconnew** [comment]
It's internal because nobody has asked for it and we don't have unit tests. My normal response is feel free to submit a PR with it made public and with unit tests, but I think you can get the information you need a different way. There are two ways to do this.

### Option 1 - ServiceDescription
You need to get a reference to the `ServiceDescription`. There are two ways to do this:
#### Option 1.1 - ConfigureAllServiceHostBase
If you use the extension method ConfigureAllServiceHostBase to register a delegate, it will get called once for every service and passed the `ServiceHostBase` for that service type. From there you can get the `ServiceDescription` from `ServiceHostBase.Description`.

#### Option 1.2 - Create an IServiceBehavior
If you create an `IServiceBehavior` and add it to DI using `services.AddSingleton<IServiceBehavior,BehaviorType>()`, then it will get called for every service in the web app. In the `ApplyDispatchBehavior` method, you get the the `ServiceDescription` passed as a parameter.

Once you have the `ServiceDescription`. you need to find the action names. Iterate over `ServiceDescription.Endpoints`. Check `ServiceEndpoint.IsSystemEndpoint` to skip a WSDL endpoint or anything else that you won't be interested in. Get `ServiceEndpoint.Contract` to get the `ContractDescription` contract object model. Iterate over `ContractDescription.Operations` to examine each `OperationDescription`. `OperationDescription.Name` will give you the name of the operation. This won't give you the action, it will give you either the method name (minus any Begin prefix or Async suffix) or the value set on the `OperationContractAttribute.Name` property. If you want the action with the namespace, then you can get that from `OperationDescription.Messages[0].Action`. This is the property that's actually used to populate `ActionMessageFilter`.  

### Option 2 - ChannelDispatcher
You will need to iterate over the `ChannelDispatcher` instances. This is a little annoying, but only a little. There's a collection `ServiceHostBase.ChannelDispatchers` which will give you the channel dispatchers. The annoying part is the collection is defined as a collection of the abstract class `ChannelDispatcherBase`, which has very little useful on it. You need to cast that to the concrete type `ChannelDispatcher`. You then iterate over `ChannelDispatcher.Endpoints`, and skip when `EndpointDispatcher.IsSystemEndpoint` is true. I suspect you already have code to get to this point as `EndpointDispatcher` has a property called `ContractFilter` which normally contains an instance of `ActionMessageFilter`. From here you can iterate over `EndpointDispatcher.DispatchRuntime.Operations` and get the action from `DispatchOperation.Action`, or the name from `DispatchOperation.Name`.


If you want to expose the type and add unit tests, feel free to submit a PR. The tests only need to be as simple as instantiating an instance and adding a few actions, then use the `Message.CreateMessage` overload which takes a `MessageVersion` and an action string. This creates a message with an empty body which is sufficient for testing this class. Then call 'ActionMessageFilter.Match` with some messages which should match and some which shouldn't with the appropriate `Assert.True` and `Assert.False` test assertions, and check that the `Actions` property contains all the actions that were added. You can test the `Match` method which takes a `MessageBuffer` by calling Message.CreateBufferedCopy()` to get a `MessageBuffer`.

**Comment by RobThree** [comment]
Oh, WOW! That's an AMAZING response. Thank you very much!

> If you want to expose the type and add unit tests, feel free to submit a PR.

I might do that, but I'll look into options 1 & 2 first. No need to make stuff public when nobody's asking for it (but me 😜 ). I have to admit that I sort-of-kind-of hacked around this already; I used reflection to get all `IServiceContracts` (sorry, doing this from memory, not at work where the code is), then enumerate all methods. Something along those lines.

I'll look into your (undoubtedly much better) options as soon as I can. Again, thank you very much. MUCH appreciated!

**Comment by RobThree** [comment]
Closing for now. Again, thank you very much for the meticulous explanation. However, my attention is currently needed elsewhere and I won't be able to revisit this for the foreseeing near future (couple of weeks). So for now I'll keep my hack in place and get back to you when I've had time to implement this much neater solution you provided. Meanwhile, there's no need to keep this issue open.

Thank you so much!
