### ISSUE TITLE
StreamedResponse not working in .net7/.net6 for WebHttp

### ISSUE THREAD

**Issue by DenisDoroshko** [CoreWCF/CoreWCF#1050]
I'm experiencing strange behavior when setting `StreamedResponse` mode for `WebHttpBinding`:
```
builder.ConfigureAllServiceHostBase(host =>
                {
                    foreach (var endpoint in host.Description.Endpoints)
                    {
                        var binding = (WebHttpBinding)endpoint.Binding;
                        binding.TransferMode = TransferMode.StreamedResponse;
                    }
                });
```
1. When I use .net7/.net6 and accept header is `*/*`, `application/json`, `application/xml` I'm getting error:
![image](https://user-images.githubusercontent.com/71182505/230064415-ddffe2a6-9c40-4caf-83b5-0a671e2fbf97.png)
`curl --location 'https://localhost:7112/Test/health' --header 'Accept: application/json'`
2. When I use .net7/.net6 and set accept header to `text/html` I'm getting successful response
`curl --location 'https://localhost:7112/Test/health' --header 'Accept: text/html'`
3. When I use net462 target framework and asp.net core 2.2.0 then it works with any accept header
**Correct me if I'm doing something wrong.**
(`Buffered` mode works fine in all cases)
Attaching test application:
[WebApplication1.zip](https://github.com/CoreWCF/CoreWCF/files/11158114/WebApplication1.zip)

**Comment by mconnew** [comment]
You need to modify your setup code to this:
```c#
            IWebHost host = CreateWebHostBuilder(args)
                .ConfigureKestrel(options =>
                {
                    options.AllowSynchronousIO = true;
                })
                .Build();
```
When using streamed mode, we don't buffer the output into a byte[] before sending, we serialize directly to the output stream. There isn't an async version of the serializer api's so the serializer writes to the stream using the synchronous api's (indirectly through an XmlWriter, but it uses the sync XmlWriter api's).
ASP.NET Core 2.x didn't have an issue with writing synchronously, but in a later version (before 6.0), ASP.NET Core had a behavior change that they considered this an error and throw. If you run your test app through a debugger, you will see an exception from ASP.NET Core about setting the AllowSynchrousIO property to true.  
You are getting a successful response because you are likely getting an error returned in the body and that error was buffered before sending asynchronously.

**Comment by DenisDoroshko** [comment]
@mconnew got it, thank you, then using `Buffered` mode is preferable, thank you for clarification
