### ISSUE TITLE
DataContractSerializer failing to serialize the response results in an aborted connection

### ISSUE THREAD

**Issue by Treit** [CoreWCF/CoreWCF#110]
If you create a WCF service method that returns an object with an IEnumerable property, and that property is backed by something DataContractSerializer can't handle, the connection gets aborted.

For instance, create a web service method that returns an object like this:

    [DataContract]
    public class Stuff
    {
        [DataMember]
        IEnumerable<string> Value { get; set; }
    }

...but in the service implementation, construct the object like so:

    public Stuff GetStuff(EchoMessage text)
    {
        return new Stuff
        {
            Value = (new string[] { "A", "B", "C" }).OrderBy(x => x)
        };
    }

Attempting to return this to the client will result in this kind of spew from Kestrel:

    info: Microsoft.AspNetCore.Server.Kestrel[34]
      Connection id "0HLUAOSVM8FV1", Request id "0HLUAOSVM8FV1:00000003": the application aborted the connection.

A .NET 4.7.2 client sees an error stating `The connection was closed unexpectedly.`

I think this should probably look to the client like a 500 error, not an unexpectedly closed connection.

**Comment by mconnew** [comment]
I checked the behavior compared with .NET Framework and they are very similar. .NET Framework closes the socket without completing the request. The difference in behavior for CoreWCF is it aborts the socket instead. So the client sees a socket reset rather than a socket close. You do get a different exception on the client in the two scenarios, but the server doesn't send a 500 response. It can't as it's already sent the HTTP response headers at that point. Do you want me to work out how to make it close the socket instead of a socket reset?

**Comment by Treit** [comment]
@mconnew Yes, I just reproduced the same type of exception on our .NET Framework service and also saw the same client behavior. If you don't see any value in changing the behavior I am ok with just punting this.

**Comment by mconnew** [comment]
I think the difference between a reset and a premature close is arbitrary from the c;lients perspective, but a reset uses less server side resources as the socket doesn't linger in TIME_WAIT. I'm closing this issue as I actually prefer the reset response from a resource usage standpoint.
