### ISSUE TITLE
Sync methods results in significant locking 

### ISSUE THREAD

**Issue by marafiq** [CoreWCF/CoreWCF#1153]
I am using the Singleton Proxy instance to call a service; it uses basicHttpBinding, resulting in significant locking.
I am only using Sync calls due to legacy code. what is the best way to use Client Proxy under load?
How to validate if there is any internal cache and it is being used?
Pooling the service client using ObjectPool, but not resulting in any performance gain in the benchmark.
Here are different ways I tried to use it - repo here - https://github.com/marafiq/wcfcoreclientprofile 

Any guidance will be helpful. I have the profiling using dot trace available; please let me know if anyone would be interested in taking a look. Otherwise, the benchmark can get some in the repo above.

![image](https://github.com/CoreWCF/CoreWCF/assets/9109259/25802474-2304-4ce8-9287-4146c1411a49)

**Comment by g7ed6e** [comment]
@marafiq It looks like the linked benchmark relates to the wcf client for dotnet core. You should address this issue to the dotnet/wcf repo instead. However having a look to the CoreWCF implementation, usage of Thread.Sleep is explicitly pausing the active thread. You should be able to provide an asynchronous implementation for the server side as long as ServiceContract and OperationContract used client side is matching.

**Comment by marafiq** [comment]
Thanks for looking into it. The latency in the service is intentional and constant 10 second to measure how the client will perform using different techniques. 

It turns out I was trying to optimize the wrong thing, the above trace turned out to be a thread starvation issue than WCF client locking. 

But I am still surprised that actually Singleton performs better than Pooled service clients when thread config adjusted. 

The use of sync method was also intentional as migrating a legacy app to net6 and it's not possible ATM to convert whole path into async.

**Comment by mconnew** [comment]
WCF Client doesn't have a sync code path implementation. When you make a sync call, it executes it asynchronously and internally blocks the thread waiting on the Task to complete. The support for sync calls is purely to support legacy code. If performance is a high priority and you have a sync code path in your app, the expectation is that sync code path will need to be made async anyway for optimal performance.  

In CoreWCF there shouldn't be any performance penalty from implementing a sync service other than any performance penalty your own service implementation code might have due to not making use of async calls.

FYI you can have a mismatch of sync and async between your client and your service. You can switch to Task based async on the client and leave your service sync. You can also do the other way around. As long as you keep the semantics of the method signature the same, it just works. E.g. `Foo DoSomething(Bar first, Bat second)` would become `Task<Foo> DoSomethingAsync(Bar first, Bat second)`

**Comment by mconnew** [comment]
Closing as there's no problems with CoreWCF itself.
