### ISSUE TITLE
[Bug]: Reference newer Nuget Microsoft.Extensions.Caching.Memory breaks Tcp-Server

### ISSUE THREAD

**Issue by AlleSchonWeg** [CoreWCF/CoreWCF#1373]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.2

### Describe expected behavior

Hi,
my Server-App uses the Microsoft.Extensions.Caching.Memory nuget for caching. Using the newest version should work. 

### Describe actual behavior

I referenced Microsoft.Extensions.Caching.Memory version 8.0.0. But with this reference a call from a client never completes. I saw that CoreWCF also used this library and i tried to downgrade my version also to version 2.1.23. Then my clients can successfully call my server. I have not tested all versions above, but with 3.1.1 the calls started to fail.

### Which binding

NetTcp

### security

None

### Which .NET version

.NET Framework

### Which os platform

Windows

**Comment by mconnew** [comment]
You're saying when you promoted the version of Microsoft.Extensions.Caching.Memory to 8.0.0 by adding a reference for your own usage, CoreWCF stopped responding to calls? I just tested changing our unit test projects to reference Microsoft.Extensions.Caching.Memory 8.0.0. I had one small compilation problem where ILoggingBuilder has moved packages and promoting this reference caused the type to be seen in two different packages. The solution was to add a package reference to version 8.0.0 of `Microsoft.Extensions.Logging.Abstractions` and `Microsoft.Extensions.Logging`. I checked NetTcp and Http and they are both functioning as expected, so there's something different that you are doing.  

Upgrading those packages caused our .NET Framework tests to fail. This is because on .NET Framework, we reference the nuget package `Microsoft.AspNetCore` to use ASP.NET Core. When running on .NET, your project needs to either use the Sdk `Microsoft.NET.Sdk.Web`, or include the following to have your app use the .NET runtime built in version of ASP.NET Core.

```
  <ItemGroup">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

If the problem isn't due to not using the right Sdk or missing the `<FrameworkReference>`, then I'm out of ideas as I can't reproduce it. Have you tried running under a debugger to see if there's any exceptions thrown which are getting swallowed? If that doesn't yield anything useful, can you provide a minimal repro project which has the problem?

**Comment by AlleSchonWeg** [comment]
> You're saying when you promoted the version of Microsoft.Extensions.Caching.Memory to 8.0.0 by adding a reference for your own usage, CoreWCF stopped responding to calls?

Hi,
yes. This is exactly what happens. I have created a repro. The repro contains a client and a server as console applications. Start both, wait until server is ready then press key in the client app. The client do this:
```C#
          var binding = new NetTcpBinding("MyBindingConfig");
          var baseUri = $"net.tcp://localhost:{22203}/";
          var url = baseUri + "dataProvider";
          var address = new EndpointAddress(url);
          var dataProviderFactory = new ChannelFactory<ICommonDataProvider>(binding, address);
          var chan = dataProviderFactory.CreateChannel();
          //CallToServer run in timeout
          var result = chan.CallToServer("Parameter");
```
In the provider project a have a reference to Microsoft.Extensions.Caching.Memory 8.0.0:
```XML
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.10.3" />
  </ItemGroup>
```
Change this to version 2.1.23, clean and rebuild solution and try again. Now the call is finished succesfully.
[ReproCoreWcf.zip](https://github.com/CoreWCF/CoreWCF/files/15106726/ReproCoreWcf.zip)
Thank you.

**Comment by AlleSchonWeg** [comment]
Hi @mconnew ,
do yo had any time to try my repro?
I changed `<Project Sdk="Microsoft.NET.Sdk">` to `<Project Sdk="Microsoft.NET.Sdk.Web">` but it's still not working. Same behavior.
Thank you.

**Comment by mconnew** [comment]
Haven't had time yet, feel free to keep bugging me as I want to work out what's going on with this.

**Comment by a-shoemaker** [comment]
I have experienced the call never completes, it just times out.  But it doesn't seem to match up with the other pieces of your scenario.  With an operation contract method that is void with no arguments a call will timeout while every other operation on the service contract works fine.  And it's only a subset of all the applications that we have using this contract (i.e., some clients work fine with the same host), but doesn't appear to be related to the version of Microsoft.Extensions.Caching.Memory.

**Comment by AlleSchonWeg** [comment]
I see that Microsoft.Extensions.Caching.Memory was updated to 6.0.1 in CoreWCF.Primitives.csproj. Now it works with CoreWcf 1.6.0

**Comment by Everyauth-limp** [comment]
> I see that Microsoft.Extensions.Caching.Memory was updated to 6.0.1 in CoreWCF.Primitives.csproj. Now it works with CoreWcf 1.6.0





https://mahara5.github.io/i0UO6ikVKlRRzJ81mTwoMVZpqHp1ALc/
