### ISSUE TITLE
How CoreWCF compares to SoapCore?

### ISSUE THREAD

**Issue by IvanFarkas** [CoreWCF/CoreWCF#14]
### How CoreWCF compares to [SoapCore](https://github.com/DigDes/SoapCore)?

See: [How SoapCore compares to CoreWCF?](https://github.com/DigDes/SoapCore/issues/273)

**Comment by mconnew** [comment]
I don't know enough about SoapCore to say anything useful.

**Comment by kotovaleksandr** [comment]
@IvanFarkas Hello! I am the first developer of the SoapCore library - a library for creating SOAP services with .NET Core. The library was written under the article https://devblogs.microsoft.com/dotnet/custom-asp-net-core-middleware-example/, later, thanks to the community, new functions appeared, such as generating WSDL, message interceptors and others. Since the .NET Core platform quickly gained popularity, the task of porting existing WCF services turned out to be very relevant and SoapCore uses relatively many users.
SoapCore cannot be compared with WCF: the first is just a library for serializing / deserializing xml messages over http, WCF is a large ecosystem with huge opportunities. At the moment, I do not understand the capabilities and status of CoreWCF, but as soon as a stable version is released that will replace SoapCore, I would recommend all our users and developers to abandon SoapCore in favor of CoreWCF. I will closely monitor the development of the project, I hope I can be useful and contribute.

**Comment by tibor19** [comment]
@kotovaleksandr I will reach out if (when) we need help with the Soap implementation.

**Comment by KamranShahid** [comment]
CoreWCF is way behind SoapCore
