### ISSUE TITLE
Got "System.NullReferenceException" when configuring endpoint's binding to BasicHttpSecurityMode.Transport

### ISSUE THREAD

**Issue by zjrobinzj** [CoreWCF/CoreWCF#145]
I configured the service in below way, and got the "System.NullReferenceException" during starting service.
![1111](https://user-images.githubusercontent.com/44034836/84555089-ecd7e100-accf-11ea-8638-d7cedaccae5f.png)

By checking the source code, I found that "HttpsTransportBindingElement _httpsTransport" was never set in HttpBindingBase, thus it’s always null. 
![2222](https://user-images.githubusercontent.com/44034836/84555163-48a26a00-acd0-11ea-986b-5fad52fe5b08.png)
![3333](https://user-images.githubusercontent.com/44034836/84555167-4dffb480-acd0-11ea-8592-f0de014c9f5c.png)

Guessing it should be bug here? Wondering how can I enable the Certificate Authentication and thus able to use OperationContext.Current.ServiceSecurityContext.AuthorizationContext.ClaimSets?

**Comment by zjrobinzj** [comment]
Looks like there is a pending fix waiting for merge already for this issue since April. Can we prioritize it?
https://github.com/CoreWCF/CoreWCF/pull/123

**Comment by StephenBonikowsky** [comment]
@mconnew Based on the #123 PR, what's the state of this issue, can the PR be merged?

**Comment by mconnew** [comment]
I have a larger PR that needs to go in to unblock some feature development. I'll look at #123 after that's merged but it's kind of irrelevant. Setting the security mode doesn't really do anything right now as ASP.NET Core is handling it all and we don't have much control of ASP.NET Core. Use the default constructor for BasicHttpBinding and configure the security in ASP.NET Core. Eventually it will mean something as it will specify what type of credentials to expect ASP.NET Core to have used and then will be able to use that in the Authorization part and populate claims, but for now use the default constructor.

**Comment by mconnew** [comment]
!'ve merged #123 now, but as I said, it's not going to solve the problem.

**Comment by mconnew** [comment]
@zjrobinzj, I made some changes to CoreWCF to expose some required classes and threw this little sample code together to enable your scenario. There isn't built in support for populating the claimset yet, but this should do the trick for you. This sample uses a thumbprint of a client certificate which was on my own machine so you will need to fix that. It also disables all certificate validation on the client and the server so you will need to address that too with whatever validation mechanism you want. Hopefully this unblocks you. You will need to use the latest packages as some extra classes were made public to support this. 

[CoreWCFClientCertSecurityContext.zip](https://github.com/CoreWCF/CoreWCF/files/4887105/CoreWCFClientCertSecurityContext.zip)

Can you let me know if this solves your issue?

**Comment by mconnew** [comment]
If you need any further help, please re-open.

**Comment by emre-toraman** [comment]
@mconnew, I believe we're having the same/related issue, can you please check?

We are able to get the client certificate from OperationContext.Current.IncomingMessageProperties["Microsoft.AspNetCore.Http.HttpContext"].Connection.Certificate, based on the sample code shared by you. But we would like to know if we lose any built-in validation and security behavior this way opposed to getting it from ClaimSets in WCF. I haven't used any client certificate validation logic on the WebHost I created with HttpSys.

```
// Configuration code
WebHost.CreateDefaultBuilder().UseHttpSys(options =>
{
	options.UrlPrefixes.Add($"https://+:443/MyService");
}).ConfigureServices(services =>
{
	services.AddServiceModelServices();
}).Configure(app =>
{
	app.UseServiceModel(serviceBuilder =>
	{
		var binding = new WebHttpBinding(WebHttpSecurityMode.Transport);
		binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;

		serviceBuilder.AddService<TService>()
			.AddServiceEndpoint<TService, TContract>(
				binding,
				address,
				endpoint =>
				{
					endpoint.EndpointBehaviors.Add(new WebHttpBehavior(app.ApplicationServices)
					{
						AutomaticFormatSelectionEnabled = false,
						HelpEnabled = false
					});
				});
	});
}).Build().RunAsync();

// Later in the service action method, ClaimSets are empty
var certificate =((X509CertificateClaimSet)OperationContext.Current.ServiceSecurityContext.AuthorizationContext.ClaimSets[0]).X509Certificate;
```

**Comment by mconnew** [comment]
The only validation WCF does with a client certificate is with the certificate validation extensibility. If you move any of that logic to use the asp.net core way of doing things, then you don't lose anything there. Beyond that it adds the claimset to give you the option of doing custom authorization based on that. The authorization happens a bit earlier in the call pipe so you avoid a bit of work by having it happen earlier if you are going to reject requests. If that's your scenario, you can still get it from the HttpContext in a custom authorization manager by pulling it from the OperationContext. So you would need to rework any code like that to examine the certificate directly instead of from the claimset. 
Not having the claimset also prevents you using a custom IAuthorizationPolicy to augment the claimset with more data. I've never seen anyone do that, but it's technically a scenario which currently won't work.

**Comment by emre-toraman** [comment]
Thanks for the detailed explanation. We had a CustomCertificateValidator which checks if the certificate is not null. We can move that to WebHost configuration. The only caveat is, we had separate ServiceHosts for each endpoint before. We are planning to use single WebHost for all services now after the migration, utilizing different ConfigureServiceHostBase per each type. Because of this, I believe we would need to configure certificate validation on WebHost according to the different service endpoints it will host (not all of them require client certificate).

Moving CustomCertificateValidator logic(checking if not null) to custom AuthorizationManager is also an option we will consider.
