### ISSUE TITLE
Roadmap of features & progress overview

### ISSUE THREAD

**Issue by cklutz** [CoreWCF/CoreWCF#159]
Hi,

first of all thanks for the effort of trying to bring WCF to .NET core in a meaningful way.

Is there some document in the repository or otherwise, that shows the progress of the project, possibly comparing it to WCF on the .NET Framework?
For my planning (and potentially even contributing) it would be interesting to know:

* what is already ported over and to what degree
* what is out of scope (due to platform or other limitations)

A potential list may be rather long or complex and I suppose involves a lot of work, depending on the level of detail.
Topic areas would be a nice start tough. Like for example, Bindings, Security, Configuration, Extensibility (*Inspector, "Context", ...), Hosting, maybe Tooling.

Casually browsing through the repository, I _think_ I have found some answers/hints, but a list in one place,
also giving notes on strategy/planning, would be really helpful. Of course, also to monitor the progress of
the project and thus factoring in this to make a planning of moving to .NET Core (from a WCF point of view).

Sorry if this has been asked before, but I was unable to find anything on the subject. 

Thanks,
Christian

**Comment by dotMorten** [comment]
Someone was just asking me about the maturity of this, and a roadmap with status of how far the porting process is and what's there/not there was the first thing I looked for.

**Comment by mconnew** [comment]
Keeping a list of what's working and what's not will become out of date as new things are ported. I plan to have a list as part of the v1 release notes. I can give you a brief overview listing the big features which are working. If there's something you use which isn't listed, the first thing to check is the unit tests. I have the attitude that if there isn't a test, it's not considered working. If you can't find a test utilizing the feature, you can ask about it. I've tried to keep the API of untested features internal to prevent an expectation of it working (but that's not 100%) so often the answer will be that it should work in theory, so clone the project, make them public and give it a go and if it works, please submit a PR including unit tests to verify it works and I'll publish a new package with it.  
Now to what is working. NetTcpBinding, BasicHttpBinding and NetHttpBinding are the transports which are working. Buffered mode works, streamed mode hasn't been tested so well so should work but might not (just checked in a fix for steamed BasicHttp). The only security modes working are transport and none. There's no integration yet into the transport security for HTTP so that needs to be configured using ASP.NET Core. For NetTcp, transport security works for Windows and Certificate credentials. Most of the extensibility points are working. You can use message inspectors, operation invokers etc. Your code should just come over with a namespace change. I've also improved the extensibility story a bit. For example, you can simply add a concrete instance of `ServiceAuthorizationManager` to DI and CoreWCF will just pick it up. You can also add an `IServiceBehavior` to DI and CoreWCF will just pick it up. I've made CoreWCF support the existing System.ServiceModel.* contract attributes from the System.ServiceModel.Primitives client package so you can reuse your contract classes in a common library without having to have two copies, one for CoreWCF and one for your client.  

The big items that are asked for which aren't working and won't be until after v1 are MTOM, reliable sessions, WSDL creation. Those are a matter of time only and a line needs to be drawn somewhere before releasing v1. These are all non-trivial features to port so have been bumped to post v1.  
Another rule I've had so far, but I think I'm going to relax it for any Windows only features are no P/Invoke's in the code base. If a feature is going to be cross platform and requires native calls, then some other component will need to own the native calls. For example, NetTcp uses NegotiateStream. NamedPipe support in WCF uses a lot of P/Invoke calls, but I've looked at the general purpose named pipe classes in .NET Core and I think we can eliminate all the P/Invoke's and just use that. So that's soft blocked to bring over as it's going to require a significant rewrite of some of the pieces. I also need to look at the ASP.NET Core named pipes implementation and see if I can use that.  

The things which can't be implemented at the moment due to lack of dependencies are full message security and distributed transactions support. Nearly everything else can be ported over, some of it needs a rewrite and some needs creative solutions.

**Comment by cklutz** [comment]
Yes, I was (maybe naively so ;-)) thinking about a list that is updated, when things are "officially" working (as having tests, etc.). But having such a list when a (new) release is available is OK as well. That is usually the version of the software that one will want to use anyway.
Nevertheless thanks for the detailed information about the current status.

**Comment by Kralizek** [comment]
@mconnew first of all, thank you for the work you're putting into this and thank you for putting down the post above.

What is exactly missing to get distributed transactions, even in a Windows-only scenario?

**Comment by mconnew** [comment]
@Kralizek, basically System.Transactions is missing the guts necessary to do it. It's got just enough pieces so the the SQL Server client can hook into it so you can manage transactions when using SQL Server. They use some internal mechanism to handle the transactions.  
I've had some ideas on how to get it working cross platform, but I just don't have the time to do it. Basically refactor the internals that should be making the native calls to expose a public interface to make the transaction piece pluggable. Then take the pieces needed to make it work on Windows (P/Invoke in native Windows libraries) and create an implementation of that interface. Then for cross platform support, an implementation can be made which uses a WCF client to proxy those calls to a service which runs on Windows and makes the calls to the native api's for you. Basically RPC the calls using WCF. You would still have a hard requirement on having a Windows machine in your network somewhere, but you have that requirement to have an MSDTC server anyway.  
The abstracted extension interface API would need to be carefully designed as ideally it would be possible to plug in an implementation which uses third party distributed transaction controllers, or even a pure WS-AT implementation.

**Comment by Danielku15** [comment]
@mconnew Do you think it will be realistic to have a CoreWCF available within Q4 2020 along .net 5? It might already help if all tasks/issues in Github would be assigned to a "v1" or "vNext" milestone. This way people could also contribute easier to the very essential parts instead of already working on new functionality. And it might answer easier the recurring question here on GH when the v1 release will come: it will come when all issues of the milestone/project-board are completed. 

While it might not be true for many people, we are mostly looking for a simple 1:1 replacement of .net Framework WCF with a .net Core WCF. Having easier integration with the ASP.net core stack is nice, but I guess also quite an effort. We're struggling to replace our SOA with WCF just easily with grpc or Rest Services without re-inventing many parts with a new proper communication system. It would be easier to convince product management to do a .net 5 migration if these parts would not need full re-development.

**Comment by mconnew** [comment]
@Danielku15, I'm currently working on getting packages ready for releasing to nuget. I'm working on getting the packages signed. Next up after that is finishing the code review for a massive PR which will enable SecurityMode.TransportWithMessageCredentials which is the foundation needed to enable WS-Federation. I'm prioritizing bug fixes and enabling peoples usage scenarios ahead of that. For example, someone reported to me internally at Microsoft with the ServiceKnownType attribute not working. It was actually that I hadn't added compat code yet for using the System.ServiceModel.ServiceKnownTypeAttribute (as opposed to CoreWCF namespaced attribute) so I quickly put together and released a fix.  
I then need to switch gears to doing some stress testing of the code to try and shake out any race conditions, and some perf testing too. Once I've done an initial run and things are looking stable, I'll move to a beta release and continue more intense testing. Once it looks like enough people are using it and there aren't many bug reports, I'll move to RTM.  
The best way to make sure it's ready for your usage is to try it out and make sure all the features you depend on are implemented. There's so many features in WCF, and many of them are barely used so the priority and roadmap really has to be demand driven, I plan to put up a special stickied issue with one comment per feature and will invite people to thumbs up the features they want to see implemented. Basically using an issue as a poor man's voting system which can have new options added later. That will be a large driver of next feature being planned.
Anything which doesn't have external dependencies missing (such as full System.Transactions support) can be ported, and even then I have some ideas around that.
If there's a feature missing which you are using, open an issue for it. If it's small, I'll quickly do it. If it's not possible, I'll let you know of potential alternatives. If it's a large work item, I'll also let you know.

**Comment by mconnew** [comment]
The roadmap will be driven by demand of features. You can register you interest in features in issue #234. Items planned for the next release will have the vNext milestone tagged.

**Comment by jrmoreno1** [comment]
@mconnew : 
Has the situation for distributed transaction changed now that https://github.com/dotnet/runtime/pull/72051 is complete?  It's windows only, but I think that isn't a problem a lot of people.

**Comment by mconnew** [comment]
Now there's support in .NET 7, we can bring this to CoreWCF. It hasn't been scheduled yet. There has been an informal internal ask from a team in Microsoft so it will likely get added to the work I'm doing later this year.

**Comment by jrmoreno1** [comment]
@mconnew : any news on DTC?
