### ISSUE TITLE
Breaking visibility changes compare to .NET ?

### ISSUE THREAD

**Issue by OhSoGood** [CoreWCF/CoreWCF#186]
Hi,
- OperationDescriptionCollection.Behaviors is public in .NET, is internal in CoreWCF (ok, there is OperationBehaviors but that still make an APi break...)
- DataContractSerializerOperationBehavior is public in .NET, is internal in CoreWCF

Could you fix it?

**Comment by danielcrenna** [comment]
@OhSoGood In WCF, `OperationDescriptionCollection` is a sub-type `Collection<OperationDescription>`, it does not have a `Behaviors` property. Is this the type you really meant?

For now, it appears that `services.AddSingleton<IOperationBehavior>(...)` is how you register behaviours.

My guess is the reason `DataContractSerializerOperationBehavior` is not yet public is that it doesn't currently implement `IWsdlExportExtension`, which make it non-compliant with the public version in ServiceModel.

**Comment by mconnew** [comment]
There is some history here. I think you are talking about on OperationDescription there are two different properties, OperationBehaviors and Behaviors. There were some api's in WCF which had two different properties declared with different types but returned the same instance, this being an example of that. One of them was attributed to prevent it showing up in intellisense as a kind of soft deprecation discouraging devs from using them. Here's the properties from .NET:

```c#
        public KeyedCollection<Type, IOperationBehavior> OperationBehaviors
        {
            get { return this.Behaviors; }
        }
 
        [EditorBrowsable(EditorBrowsableState.Never)] 
        public KeyedByTypeCollection<IOperationBehavior> Behaviors
        {
            get { return behaviors; }
        }
```

As the intention was to phase out usage of the KeyedByTypeCollection properties, they haven't been brought across. If they are still in the source code, that's a mistake and needs cleanup. As you can see, they return the exact same thing. So just use the more descriptive property name to access the property.  
Part of the development of CoreWCF is to try and move away from there being 20 ways to do the same thing and try and be a bit more prescriptive, but only in ways which require minimal code changes like changing which property you use. I know this can be annoying, but I'll give you a simple example how this helps. If you are looking for all code which adds a behavior, you now only need to look for usage of a single property instead of two. It's possible someone doesn't know or forgot in the moment about there being two properties so when they are searching their code base, they could miss some instances.  

DataContractSerializerOperationBehavior is now public. The IWsdlExportExtension issue means the surrogate property isn't exposed yet as there's some problems around that which still need to be resolved.
