### ISSUE TITLE
Service operation with ref or out parameter returns null for the parameter on Client

### ISSUE THREAD

**Issue by imcarolwang** [CoreWCF/CoreWCF#196]
Service operation with ref/out parameter is invoked, but Client get null value for the ref/out parameter.

**Comment by JoelDavidLang** [comment]
I'm having what I believe is a related issue. When the server uses the invoke delegated generated in the InvokerUtil class it throws an ArgumentException. This is because the particular method I'm calling has a _bool_ parameter after an _out Guid_ parameter and the invoker delegate code does not handle it properly.

I intend to fix the problem and make a pull request.
