### ISSUE TITLE
Add Azure Pipelines for CI

### ISSUE THREAD

**Issue by nschonni** [CoreWCF/CoreWCF#21]
Would be good to have the tests run on PRs to make sure nothing is breaking. Since this is a OSS project, it should be able to leverage the free offering

**Comment by mconnew** [comment]
@jongalloway, my understanding is that the .NET Foundation has something available around this?

**Comment by Daniel-Svensson** [comment]
@mconnew with the current free offering for azure pipelines for OSS projects I think you will be more than fine with a CoreWCF organization+project in azure pipelines.

In any case setting up a pipeline now with YAML build would prove benefits directly and would be easily moved to run on any foundation specific azure account in the future it there are any other upsides to it.

Would you be interested in receiving a PR for a [working CoreWCF azure pipelines build pipeline](https://svensson-daniel.visualstudio.com/CoreWCF/_build/results?buildId=467
) ?
Since the current sln include desktop projects I can submit a windows build and test pipeline.

**Comment by mconnew** [comment]
We now have CI building in AzDO
