### ISSUE TITLE
Use on Desktop without ASP.net Core

### ISSUE THREAD

**Issue by Danielku15** [CoreWCF/CoreWCF#227]
Hi there. 

I thought of giving CoreWCF a try and see if our product might already work with it. But it seems that the migration path for desktop applications is not really set yet in CoreWCF. 

With this issue I want to clarify whether there is a planned 1:1 migration path support in CoreWCF for applications using `ServiceHost`. If was a bit surprising to see that CoreWCF does not start off with a simple .net core WCF version but rather aims already for a tight coupling with ASP.net core and related infrastructure. I was hoping different. Goal for us as a first step would be to simply exchange System.ServiceModel with CoreWCF and make the required namespace adjustments. Unfortunately there is no port of the old `ServiceHost` but there is already some code add support for ASP.net core which we do not plan to use yet  until we migrated some other aspects of our application. 

The [roadmap discussion](https://github.com/CoreWCF/CoreWCF/issues/159) sounded like the release is about to be prepped once the open construction sites are closed.  

Ad: I think the [DesktopServer sample](https://github.com/CoreWCF/CoreWCF/tree/master/src/Samples/DesktopServer) should be deleted from this repository, it is misleading as it is not using CoreWCF but simply using the normal WCF from .net Framework 4.x

**Comment by mconnew** [comment]
This isn't a straight port of WCF Server/ServiceHost. To do a straight port would have made cross platform support almost impossible. It would have meant more code in the repo, meaning more code which needs to be maintained and a higher chance of bugs on non-windows platforms.
A straight port would cause you problems with running something like an MVC website on the same port as a WCF service as MVC would now be built on top of ASP.NET Core and could be using Kestrel which makes sharing the same port really difficult.
A straight port would have required re-implementing .NET Core to IIS hosting otherwise you couldn't host your app in IIS. By building on top of ASP.NET Core, you can host your app in IIS.

WCF on .NET Framework wasn't ever tied to a single hosting model. For example, to host in IIS you would use a .svc file. WCF was always ambidextrous as to how it was hosted which is why all the api's for extensibility gave you a ServiceHostBase. For example `IServiceBehavior.ApplyDispatchBehavior(ServiceDescription, ServiceHostBase)` ([docs here](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.description.iservicebehavior.applydispatchbehavior?view=netframework-4.8)) would pass you a `ServiceHostBase` and not a `ServiceHost`.  
With WCF on .NET Framework having multiple hosting models and multiple configuration mechanisms, namely self hosted where you new up an instance of ServiceHost, and IIS hosted with an svc file and configuration vs code, CoreWCF is aimed at the experience being similar to adding a new hosting model and a new but similar configuration method.  

The compatibility aim is that you should be able to:
* Use your contract as is with some caveats
* Use your existing service implementation with minimal changes
* Use your same extensibility implementations with minimal changes
* Continue using your same clients unmodified  

### Use your contract as is with some caveats
The contract attributes in .NET Core are defined in the WCF Core client packages and so are missing some properties you might want to use on the server side. If that's the case, then switch the namespace in your using's to CoreWCF and the attribute properties you need should be available. Either namespace should work though. 99% of developers should just be able to use their existing contracts with no changes though.

### Use your existing service implementation with minimal changes
The kinds of changes you might need to make are namespace changes if you are referencing OperationContract.Current for example. Anything security related (SecurityContext.Current) hasn't been wired up yet. This is because more work needs to be done to integrate this into the ASP.NET Core security middleware. The major ask people have had around this is client certificates and I've been able to provide some sample code to wire up SecurityContext claims to get the same behavior.

### Use your same extensibility implementations with minimal changes
Most `IServiceBehavior` or `IEndpointBehavior` based extensibility points should work with just a namespace switch. There might be some properties on some of the classes that are missing. That's purely because they haven't been tested yet. I'm reluctant to expose an API without tests verifying that API works. So if there's something missing, open an issue and it's usually the case of making it public and writing a quick test to validate it works. I've plumbed in `RemoteEndpointMessageProperty` and added support for `HttpRequestMessageProperty` and `HttpResponseMessageProperty`. Basically nearly anything pre-existing should be supportable, it's just a matter of asking. There's so much surface area it's a case of getting your need to the front of the queue by opening an issue.  

### Continue using your same clients unmodified
I'm going to lump into here as it's related that you can use the same out-of-box bindings. So if you are using NetTcpBinding with Windows client credentials, then you configure your binding the same way, and the client doesn't need to make any changes.

The DesktopServer sample app is there to demonstrate interop between all client and server combos of .NET Framework and .NET Core. It's also there as a template of equivalence. You can open the Core server code and the Desktop server code and see where the same pieces get used in the two implementations. BTW, CoreWCF runs just fine on top of .NET Framework as it only has a dependency on .NET Standard 2.0 and ASP.NET Core 2.1. This was intentional, to disconnect the dependency on porting to CoreWCF and porting to .NET Core at the same time. The idea is you can get everything working on CoreWCF with all your existing code and once you are happy that's working, you can start working on the changes to your service implementation to get it working on .NET Standard 2.0/.NET Core.

Another reason not to do a straight port is the code base in the original .NET Framework WCF uses and abuses the APM pattern to such an extreme that it's nearly impossible for anyone who isn't working with the code on a regular basis to be able to understand and follow the code. Have you ever tried to debug an APM style while(true) loop which goes async on every iteration and doesn't use any loop keywords (for/while/do etc) anywhere? That isn't a good situation to be in for an open source project. So this is a rewrite of a lot of the guts of WCF to use async/await Task based programming all the way through. There's only APM code in a small handful of places.

I know you would like to just retarget your code and it just work, but that just isn't doable in a sustainable way. The alternative to CoreWCF was nothing. I had to make some architectural decisions to make it so I wasn't the only one who could work on the code and to make it a sustainable open source project. I needed to make it so someone could just pick up a debugger and try and solve their own problem.

If you need some help working out how something from .NET Framework translates, feel free to open an issue.

**Comment by Danielku15** [comment]
Thanks a lot again for the comprehensive explanation behind your plans. It helps understanding your design decisions. I gave it a shot a while ago to compile some basics of the original WCF source (via referencesource). I got quite far but also hit some large walls when it came to certain modules like security, transactions and some other bits&pieces not available in .net core. I bet this was also when this project might have changed paths and rather went for making it proper and clean. 

I might have been overthinking the topic on our side anyhow. Creating an own "ServiceHost"-look-a-like class which just maps down to an ASP.net core WebHost should be quite a straight forward task. At least in our case we just use some very basics of the ServiceHost like registering of behaviors and starting/stopping it. If I will hit a wall there I will try to file a more dedicated issue on how to port certain things over. 

Anyhow it might be worth noting such things down somewhere. Maybe in a Wiki on GH? It seems you have put in quite some thoughts in the path of CoreWCF already, but it seems people keep asking the similar questions. Some basics like: 

* Details on how the project started and who's behind it. (to inform people a bit who are the main drivers and what to expect from the team size)
* How it evolved from the original source code and what the new strategy behind CoreWCF is (what you wrote here)
* How the roadmap to the final release and maybe how the next steps&goals afterwards will look like. 

I'm looking forward to the "GitHub Discussions" feature which will be released in Q4-2020. I think it will provide a bit a better platform for discussion than just issues 😉  Thanks again for all your effort and stay healthy.
