### ISSUE TITLE
Open up  FaultContractInfo

### ISSUE THREAD

**Issue by WenningQiu** [CoreWCF/CoreWCF#341]
Our applications implement IErrorHandler that needs to access the fault contract information on service operations. Such applications do not compile with CoreWCF as CoreWCF.Dispatcher.DispatchOperation.FaultContractInfos and related types are taken internal.

Would it be possible to open up those properties and related types such that CoreWCF public API remains compatible with WCF?

**Comment by mconnew** [comment]
I have a general policy that if we don't have a test, the api isn't made public. The fastest way to get this would be to contribute a unit test which uses this api and validates expected behavior? Otherwise it will get put on the TODO list and might be a while. I'm not familiar with that api, I had a quick look and it looks like it's just a description of a FaultContract attribute converted to more concrete SOAP concepts? If so, then adding a test contract with a FaultContract then adding a behavior which validates the information gets propagated would be sufficient testing.

**Comment by g7ed6e** [comment]
Hi I added the suggested unit test and made the FaultContractInfos property public.

**Comment by WenningQiu** [comment]
@g7ed6e Thanks you!
