### ISSUE TITLE
Build warnings related to un-used fields

### ISSUE THREAD

**Issue by Treit** [CoreWCF/CoreWCF#37]
Problem:
There are close to 50 warnings when you build Core WCF, mostly CS0067 (event 'x' is never used), CS0169 (field 'x' is never used) and CS0649 (field 'x' is never assigned to.)

Steps to repro:
Run `dotnet build -t:rebuild` from the src folder.

Expected Result:
The build is clean with no warnings.

Actual Result:
There are 47 build warnings.

Notes:
I have attached the full list of warnings.
[corewcf_build_warnings.txt](https://github.com/CoreWCF/CoreWCF/files/3597304/corewcf_build_warnings.txt)

**Comment by mconnew** [comment]
This is known. There's still some cleanup to do. Some of those are false alarms such as events from an implemented interface. Some of them are there because some functionality still needs to be put back in and there's no point in cleaning up just to put it back again. Some of them are remnants of functionality we can't implement such as transactions and I missed something in the cleanup.  
I intend to have it clean before a 1.0 release.

**Comment by mconnew** [comment]
All build warnings now cleaned up.
