### ISSUE TITLE
CoreWCF nuget package is not found on nuget.org, makes it difficult to use the Sample projects

### ISSUE THREAD

**Issue by BiancoA** [CoreWCF/CoreWCF#386]
When trying to explore one of the sample projects, https://github.com/CoreWCF/CoreWCF/tree/main/src/Samples/NetCoreServer for example, 

![grafik](https://user-images.githubusercontent.com/6458284/127336960-cb8f812b-8b38-48b1-8c89-82a192a2a594.png)

when looking for the package(s) only three are found:

![grafik](https://user-images.githubusercontent.com/6458284/127337076-5df50e39-3b99-4e30-bdb1-7f613d9e5542.png)

Is there something I am doing wrong?

**Comment by birojnayak** [comment]
here is the link if you need = > https://www.nuget.org/profiles/corewcf

Below is the image... check your nuget package manager config

<img width="1258" alt="Screen Shot 2021-07-28 at 12 39 27 PM" src="https://user-images.githubusercontent.com/49173255/127385356-07318bdc-1d38-4059-b972-fe34d4e6e999.png">

**Comment by BiancoA** [comment]
thank you! I was a bit confused by the naming convention. Adding all 3 packages made it work

**Comment by mconnew** [comment]
The issue you were hitting is the sample project is pointing to the devops pre-release nuget server and not nuget.org. It looks like you have this resolved now. We have 0.2.1 packages available on nuget.org and there's some new features and bug fixes so that's probably the best version to experiment with.
Closing the issue as you're unblocked, feel free to reopen if you continue to have problems.
