### ISSUE TITLE
`OperationFormatUse.Encoded` use of `XmlSerializerFormatAttribute` throws PlatformNotSupportedException

### ISSUE THREAD

**Issue by petarpetrovt** [CoreWCF/CoreWCF#397]
I am trying to migrate an existing WCF service to .NET 5.0 via CoreWCF.
Starting the asp.net core application throws `PlatformNotSupportedException` when the `Use` property of the `XmlSerializerFormatAttribute` attribute is set. Removing it dont throws but the invocation always returns null (debugging the service there is a correct result returned in the implementation).

```csharp
[CoreWCF.OperationContractAttribute(Action = "uri:egovmsg/GetAllRecords")]
[CoreWCF.XmlSerializerFormatAttribute(Style = CoreWCF.OperationFormatStyle.Rpc, Use = CoreWCF.OperationFormatUse.Encoded)]
[return: CoreWCF.MessageParameterAttribute(Name = "return")]
EGovMessageDir GetAllRecords();
```

**Comment by petarpetrovt** [comment]
This is the output of the integration test:
```
Message: 
Class Initialization method IntegrationTests.RegistryServiceTests.ClassInitialize threw exception. System.PlatformNotSupportedException: System.PlatformNotSupportedException: Operation is not supported on this platform..

Stack Trace: 
OperationReflector.EnsureMessageInfos()
Reflector.EnsureMessageInfos()
OperationReflector.get_Request()
XmlSerializerOperationBehavior.CreateFormatter()
IOperationBehavior.ApplyDispatchBehavior(OperationDescription description, DispatchOperation dispatch)
DispatcherBuilder.BindOperations(ContractDescription contract, ClientRuntime proxy, DispatchRuntime dispatch)
DispatcherBuilder.InitializeServiceHost(ServiceHostBase serviceHost, IServiceProvider services)
DispatcherBuilder.BuildDispatcher[TService](ServiceConfiguration`1 serviceConfig, IServiceProvider services)
ServiceConfiguration`1.GetDispatchers()
DispatcherBuilderImpl.BuildDispatchers(Type serviceType)
ServiceModelHttpMiddleware.BuildBranch()
ServiceModelHttpMiddleware.EnsureBranchBuilt()
ServiceModelHttpMiddleware.ServiceBuilderOpenedCallback(Object sender, EventArgs e)
CommunicationObject.OnOpened()
--- End of stack trace from previous location ---
WrappingIServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
WebHost.StartAsync(CancellationToken cancellationToken)
RegistryServiceTests.ClassInitialize(TestContext _) line 47
```

**Comment by mconnew** [comment]
Wow, this is some long ago ported code. I just looked at this problem and the reason why this isn't supported is at the time of porting, `SoapReflectionImporter` wasn't available yet and the current latest supported standard was netstandard 1.7!! That tells you how long ago I started porting this. 

This should be an easy fix. The problem is [in this file](https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Primitives/src/CoreWCF/Description/XmlSerializerOperationBehavior.cs#L699) in the `XmlSerializerImporter` class. Basically need to uncomment all references to SoapImporter and it's backing field, and fix the naming of the backing field to start with `_`.  

Would you have the time to submit a PR with this fix along with a test which uses these options?

**Comment by petarpetrovt** [comment]
Sure, I will fix it.
