### ISSUE TITLE
IDispatchMessageFormatter is internal

### ISSUE THREAD

**Issue by jeroen-cordfunke** [CoreWCF/CoreWCF#492]
In the namespace CoreWCF.Dispatcher, there is an interface defined called IDispatchMessageFormatter. In WFC this interface is public, in CoreWFC this interface is internal. This makes it impossible to implement IDispatchMessageFormatter in our code. Can this member be made public?

```
namespace CoreWCF.Dispatcher
{
    internal interface IDispatchMessageFormatter
    {
...
    }
}
```

**Comment by mconnew** [comment]
The general policy is if we don't have a test, it's not considered working so will usually be internal. In 99% of cases, just making it public is all that's needed. Would you be able to submit a PR to make this public as well as the api where this is set and write a simple unit test to validate it. Obviously the message formatter functionality is working otherwise CoreWCF just wouldn't work, it's more a matter of making sure the extensibility point is used when set. This could be as simple as writing a wrapping implementation which wraps and delegates to the existing implementation and sets a flag for each of the methods to record it was called. In the test make a service call and make sure the flags were set proving the extensibility point was utilized.  
If you have the time to do that, then I can create a new package relatively quickly. We have a few other PR's about ready to merge so I was going to publish a new package soon anyway.

**Comment by jeroen-cordfunke** [comment]
I'm new to github, but I will give this a try, hopefully tomorrow.

**Comment by mconnew** [comment]
If you need any help or get stuck with something, feel free to ask. Here's the general flow I use.
1. Fork the repo into your own account. There's a button at the top right. My fork then has the url https://github.com/mconnew/CoreWCF.git
2. Clone my fork locally. So for me that was running `git clone https://github.com/mconnew/CoreWCF.git`
3. I then add this main repo as an upstream repo. So change to your cloned folder and run `git remote add upstream https://github.com/CoreWCF/CoreWCF.git`. Then update local view by running `git fetch --all --prune`
4. Make a local branch for changes. `git checkout -b IDispatchMessageFormatter`
5. Make any changes and commit locally.
6. If there's been any changes committed to the upstream repo, rerun `git fetch --all --prune`. Switch to main branch, `git checkout main`, and update with upstream `git merge --ff-only upstream/main`. Switch back to changes branch `git checkout IDispatchMessageFormatter` and then rebase to main, `git rebase main`. This pulls in any changes from main ahead of your own changes. If there's any conflicts in your commits, you will need to fix them. Running `git status` tells you which files have the conflicts and the process of resolving them.
7. When your changes are ready to be merged, push to your remote, `git push origin IDispatchMessageFormatter`.
8. Go to https://github.com/CoreWCF/CoreWCF and it will ask you if you want to open a PR for your recently pushed branch. The steps should be pretty self explanatory.
9. If there's any changes needed based on feedback, make a new commit locally and push those changes again to your remote. The PR will automatically be updated with the new commit.

If you have any problems, just ask.

**Comment by DawnDevelop** [comment]
I was about to open a PR when I realized that the Issue was already addressed [here](https://github.com/CoreWCF/CoreWCF/commit/0cc1f97f72458814137cce05de93774594596e10#diff-1c79e1459d79115e432c14d81e265fdad663206c5fb1375f6503571370ab6c74R8) in Commit 0cc1f97f72458814137cce05de93774594596e10

**Comment by mconnew** [comment]
The interesting thing is that to shoehorn a REST request into a SOAP based programming model, you have to use most of the extensibility points to get it to work 😀. That feature will have satisfied most people's extensibility requirements.
