### ISSUE TITLE
OperationContext.Current is null

### ISSUE THREAD

**Issue by KaNarlist** [CoreWCF/CoreWCF#529]
Hi, I'm trying to migrate a .Net Framework 4.8 WCF service to .Net 5.0 and CoreWCF. One problem I ran into is, that OperationContext.Current is null in my service methods. We use it to access OperationContext.Current.RequestContext.RequestMessage.Headers where the client added some custom headers.

It doesn't matter wether I host the service in Kestrel or IIS Express.

Is OperationContext.Current supposed to be set in CoreWCF or is there another way to access the wcf Message?

**Comment by mconnew** [comment]
You are probably using the System.ServiceModel version of OperationContext. You need to switch to using the CoreWCF namespaced version.

**Comment by KaNarlist** [comment]
You are of course correct. Don't know how I've missed that. Thank you!

**Comment by patheems** [comment]
> You are probably using the System.ServiceModel version of OperationContext. You need to switch to using the CoreWCF namespaced version.

Hi @mconnew, I'm trying to use the `OperationContextScope` like in the example https://github.com/CoreWCF/CoreWCF/blob/50526d069fbadfb0cef4b005c9ad132264e24494/src/CoreWCF.Http/tests/HttpRequestMessagePropertyTests.cs#L45

but does this mean I need to keep using the `System.ServiceModel` version because I can't find a CoreWCF variant of the OperationContextScope...???
