### ISSUE TITLE
Test hangs when running under .Net Framework

### ISSUE THREAD

**Issue by Daniel-Svensson** [CoreWCF/CoreWCF#53]
When preparing a CI pipeline (#52) for the project everything worked well until I updated to the latest master which included #50 after that the tests running under net framework hangs and never completes.

I have not done any debugging to se what fails yet but you can find the CI log at 
https://svensson-daniel.visualstudio.com/CoreWCF/_build/results?buildId=625

**Comment by mconnew** [comment]
I did see a single semi-hang locally when I ran the tests but then it went away and I couldn't repro it. Looking at the logs, although I don't believe it's the direct cause of the hang, there is some extra exception handling required [here](https://github.com/CoreWCF/CoreWCF/blob/master/src/CoreWCF.NetTcp/src/CoreWCF/Channels/Framing/FramingModeHandshakeMiddleware.cs#L41). Basically the code assumes the exception will be a CommunicationException but we're not in Kansas anymore and it's not WCF code handling the socket so that catch clause needs to be expanded to handle Microsoft.AspNetCore.Connections.ConnectionAbortedException.  

I suspect I know what the general cause of the hang is. When using a ConnectionHandler in ASP.NET Core 2.1, if you don't explicitly complete the pipes, the socket stays around even after the WebHost has shutdown. I opened an issue aspnet/AspNetCore#13292 for this. Basically NetTcp client pools the connections after you close the channel at a process wide level. When the next test runs, it picks up an idle connection from the pool and tries to send the connection preamble. There's nobody listening on the other end so the channel Open only completes when the open timeout fires. If this is the cause, it can be validated by modifying the client NetTcpBinding connection pool settings to not pool any connections. If this works, then it's this bug that's being triggered. I did register a delegate to the app lifetime handler for shut down to close the transport pipes and this should have dealt with this issue so there must be some race condition somewhere. Especially as #50 didn't add any transport using tests. I only added tests using the Dispatcher directly and AspNetCore isn't actually used.

**Comment by Daniel-Svensson** [comment]
You are probably correct but i did find it strange that the netcoreapp2.1 version did not suffer at all.
I may have been unlucky but I had a 100% repro rate with the lastest master (including #50) for net472 only and 0% without that commit so I do suspect it to interact somehow, It make sens to fix the issues you identified and then retry again.

**Comment by Daniel-Svensson** [comment]
Notes: I think there are more exception types which should be handled. 
At least ConnectionResetException and IOException as well based on my understanding of the [source code of SocketConnection](https://github.com/aspnet/AspNetCore/blob/release/2.1/src/Servers/Kestrel/Transport.Sockets/src/Internal/SocketConnection.cs)

I have not found any documentation which hints what kind of exception one should expect. Most examples from documentation does no exception handling, or have a general Exception catch.
Maybe the latter around ReadAsync (and WriteAsync) on the pipe would work and be somewhat future proof even if it is not an elegant solution

**Comment by Daniel-Svensson** [comment]
This seems fixed so closing it
