### ISSUE TITLE
NetTcp binding: NullReferenceException on the server when using wrong end point address on the client

### ISSUE THREAD

**Issue by cyanite** [CoreWCF/CoreWCF#530]
I accidentally used "IFoo" instead of "Foo" in the service URL on the client (something like "net-tcp://localhost/Some.Namespace.IFoo"), and it didn't work, since the endpoint was exposed with "Foo". After debugging, I see that it throws a NullReferenceException on the server. This happens in `NetMessageFramingConnectionHandler.cs`, in the method `BuildHandshake`. It calls `GetServiceHandshakeDelegate` and then immediately calls the returned delegate. Unfortunately,  `GetServiceHandshakeDelegate` simply returns null if no suitable delegate is found, apparently when you use a wrong endpoint.

I feel the framework should never throw a NullReferenceException in any situation. I'd be happy to help with a PR, if possible.

**Comment by mconnew** [comment]
You're right, that is a bug. There's a special endpoint not found sequence the service needs to send back to the client. It's not a SOAP message, it's part of the NetMF Framing protocol. The approach I would take is to have a default handler which does this that GetServiceHandshakeDelegate would return instead of null. If you need help finding the code which sends back that byte sequence, let me know. It should be relatively quick for me to dig out.

**Comment by cyanite** [comment]
I created a pull request. No tests yet, but a take on the implementation. It works for me in local testing; I now get correct faults on the client.

**Comment by mconnew** [comment]
The fix was merged
