### ISSUE TITLE
Dependency Injection in services

### ISSUE THREAD

**Issue by KaNarlist** [CoreWCF/CoreWCF#533]
I saw some issuses talking about Dependency Injection, but I'm not sure if what I am trying to do is supported by Core WCF or not.
Basically I want to inject something into my services. My Startup class looks like this:

```c#
public void ConfigureServices(IServiceCollection services)
{
	services.AddServiceModelServices();
	services.AddSingleton<IDataAccessFactory>(new DataAccessFactory(Configuration.GetConnectionString("M1DBConn")));
	services.AddSingleton<ISpecialUserValidator, SpecialUserValidator>();
	services.AddSingleton<UserValidator>();

	//add services, because dependency injection is not working otherwise
	services.AddSingleton<CustomerService>();
}

public void Configure(IApplicationBuilder app, UserValidator userValidator)
{
	userPasswordBinding = new WSHttpBinding(SecurityMode.TransportWithMessageCredential);
	userPasswordBinding.Security.Message.ClientCredentialType = MessageCredentialType.UserName;

	srvCredentials = new ServiceCredentials();
	srvCredentials.UserNameAuthentication.UserNamePasswordValidationMode = UserNamePasswordValidationMode.Custom;
	srvCredentials.UserNameAuthentication.CustomUserNamePasswordValidator = new ServiceAuthenticator(userValidator);

	app.UseHttpsRedirection();
	
	ServiceAuthorizationBehavior authBehavior = app.ApplicationServices.GetRequiredService<ServiceAuthorizationBehavior>();
	var authPolicies = new List<IAuthorizationPolicy>
	{
		new ServiceAuthorizationPolicy(userValidator)
	};
	var externalAuthPolicies = new ReadOnlyCollection<IAuthorizationPolicy>(authPolicies);
	authBehavior.ExternalAuthorizationPolicies = externalAuthPolicies;
	authBehavior.PrincipalPermissionMode = PrincipalPermissionMode.Custom;

	app.UseServiceModel(builder =>
	{
		ConfigureService<CustomerService, ICustomerService>(builder);
	});
}

void ConfigureService<TService, TContract>(IServiceBuilder builder) where TService : class
{
	builder.ConfigureServiceHostBase<TService>(host =>
	{
		host.Description.Behaviors.Add(srvCredentials);
	});
	builder.AddService<TService>().AddServiceEndpoint<TService, TContract>(userPasswordBinding, string.Format("/{0}", typeof(TService).Name));
}
```

CustomerService has one contructor that expects one parameter of IDataAccessFactory. If I call AddSingleton for CustomerService  everything works as expected. But if I don't do this (and I would prefer to not have to do this extra step for each service class) CustomerService is only created if it has a default constructor, otherwise when calling the service the client gets a Fault saying "The service implementation object was not initialized or is not available".

**Comment by mconnew** [comment]
This is expected behavior. WCF on .NET Framework has the constraint that if you don't supply a service instance and instead pass the type of your service instance, that type must have a default constructor. So if you were using WCF on .NET Framework you would need a default constructor.  
In CoreWCF we've added the support to check DI first to see if we can get the service instance from there. If we can't get the instance from DI we fall back to the old WCF behavior which requires a default constructor. To have CoreWCF pull from DI all the constructor dependencies and pass them to the constructor of your type would be duplicating functionality of the DI system.  
I can think of a few options to provide additional ways to get the instance to CoreWCF. One option would be to add an overload for `IServiceBuilder.AddService` which accepts an existing instance. That would require you to get the constructor parameters from DI yourself (either by adding them to Configure method args or pulling from app.ApplicationServices) and creating an instance yourself. That seems like a lot more work than just adding a singleton to DI. Another option is to create a custom `IInstanceProvider` which basically does the same thing, but can be used for non-singleton services. There are plenty more, but I want to avoid writing an inline blog post about 1001 ways to instantiate your service instance.   

Can you explain the problem with adding the `CustomerService` instance to DI? There might be a simple alternative solution doing something with generics. The way your `ConfigureService` method is written, I get the impression this is a simplification of your scenario, and you have a large number of services. If that's the case, a reflection based approach in `ConfigureServices` might work to automatically populate DI with all your service types. Basically, look for all interfaces which have the `ServiceContractAttribute` attribute applied, then find all types which implement those interfaces, then add them all to DI.  

Btw, best practice is to call `host.Description.Behaviors.Remove<ServiceCredentials>()` in case something else has triggered the credentials being automatically created (this can happen by accessing `host.Credentials`) or already added them via a behavior.

**Comment by KaNarlist** [comment]
Thank you for your in depth reply. Yes I have around a dozen services currently, with new ones being added regularly. I thought about a reflection based solution too, if it's not working out of the box. But I'm not sure if it's overkill. Having to add the service manualy to DI is not nice, but it's not a big problem either and I can live with it for now.

Thanks for the credentials tip too!

**Comment by Kralizek** [comment]
@KaNarlist you could look at Scrutor. It's a library that adds scanning capabilities to Microsoft.Extensions.DependencyInjection

https://github.com/khellang/Scrutor

**Comment by dpbevin** [comment]
I was able to add constructor-based DI (in .NET Framework and .NET 5+) using a custom behavior that implemented `IInstanceProvider`.

A .NET 6 version might look a bit like this...

Step 1: Register the service (and deps with DI): `services.AddSingleton<CustomerService>();`

Step 2: Add the custom behavior to the host:
```
builder.ConfigureServiceHostBase<CustomerService>(host =>
{
    var serviceScopeFactory = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>();
    var instanceProvider = new DependencyInjectionInstanceProvider<CustomerService>(serviceScopeFactory);
    host.Description.Behaviors.Add(instanceProvider);
});
```

The `DependencyInjectionInstanceProvider` looks a bit like this:
```
using CoreWCF;
using CoreWCF.Channels;
using CoreWCF.Description;
using CoreWCF.Dispatcher;
using System.Collections.ObjectModel;

namespace CoreWcf.Extensions;

public class DependencyInjectionInstanceProvider<TService> : IInstanceProvider, IServiceBehavior
    where TService : class
{
    private readonly IServiceScopeFactory serviceScopeFactory;
    private readonly Dictionary<InstanceContext, IServiceScope> scopesTargets = new Dictionary<InstanceContext, IServiceScope>();

    public DependencyInjectionInstanceProvider(IServiceScopeFactory serviceScopeFactory)
    {
        this.serviceScopeFactory = serviceScopeFactory ?? throw new ArgumentNullException(nameof(serviceScopeFactory));
    }

    public object GetInstance(InstanceContext instanceContext, Message message)
    {
        return this.GetInstance(instanceContext);
    }

    public object GetInstance(InstanceContext instanceContext)
    {
        // Create a .NET dependency injection "scope" for each WCF service instance
        var scope = this.serviceScopeFactory.CreateScope();
        var serviceHost = scope.ServiceProvider.GetRequiredService<TService>();

        this.scopesTargets[instanceContext] = scope;

        return serviceHost;
    }

    public void ReleaseInstance(InstanceContext instanceContext, object instance)
    {
        if (this.scopesTargets.TryGetValue(instanceContext, out var tuple))
        {
            this.scopesTargets.Remove(instanceContext);
            tuple?.Dispose();
        }
    }

    public void Validate(ServiceDescription serviceDescription, ServiceHostBase serviceHostBase) { }

    public void AddBindingParameters(ServiceDescription serviceDescription, ServiceHostBase serviceHostBase, Collection<ServiceEndpoint> endpoints, BindingParameterCollection bindingParameters) { }

    public void ApplyDispatchBehavior(ServiceDescription serviceDescription, ServiceHostBase serviceHostBase)
    {
        foreach (var channelDispatcherBase in serviceHostBase.ChannelDispatchers)
        {
            var cd = (ChannelDispatcher)channelDispatcherBase;
            foreach (var ed in cd.Endpoints)
            {
                if (!ed.IsSystemEndpoint)
                {
                    ed.DispatchRuntime.InstanceProvider = this;
                }
            }
        }
    }
}

```
