### ISSUE TITLE
WSHttpBinding with Windows Authentication not working

### ISSUE THREAD

**Issue by KaNarlist** [CoreWCF/CoreWCF#535]
I hope this is the last one to bugger you with. I'm trying to get Windows Authentication working for a Single Sign On use case, but I always get a SecurityNegotiationException in the client.

In the original .Net Framework WCF application each service has two endpoints configured and one of them uses this binding:

```
<wsHttpBinding>
	<binding name="ssoBinding">
	  <security mode="TransportWithMessageCredential">
		  <transport clientCredentialType="Windows" />
		  <message clientCredentialType="Windows" />
	  </security>
	</binding>
</wsHttpBinding>
```

my test client basically looks like this

```
ssoBinding = new WSHttpBinding();
ssoBinding.Security.Mode = SecurityMode.TransportWithMessageCredential;
ssoBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;
ssoBinding.Security.Message.ClientCredentialType = MessageCredentialType.Windows;

var wcfFacotory = new System.ServiceModel.ChannelFactory<ICustomerService>(ssoBinding, new EndpointAddress(url));
var channel = wcfFacotory.CreateChannel();
```

If I call a service method in the client, I get an authenticated WindowsIdentity instance of the client windows user in my AuthorizationPolicy on the server.

Now in my Core WCF server I tried to do the same:

```
public void Configure(IApplicationBuilder app, UserValidator userValidator)
{
	userPasswordBinding = new WSHttpBinding(SecurityMode.TransportWithMessageCredential);
	userPasswordBinding.Security.Message.ClientCredentialType = MessageCredentialType.UserName;

	ssoBinding = new WSHttpBinding(SecurityMode.TransportWithMessageCredential);
	ssoBinding.Security.Message.ClientCredentialType = MessageCredentialType.Windows;
	ssoBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;

	srvCredentials = new ServiceCredentials();
	srvCredentials.UserNameAuthentication.UserNamePasswordValidationMode = UserNamePasswordValidationMode.Custom;
	srvCredentials.UserNameAuthentication.CustomUserNamePasswordValidator = new ServiceAuthenticator(userValidator);

	app.UseHttpsRedirection();
	
	ServiceAuthorizationBehavior authBehavior = app.ApplicationServices.GetRequiredService<ServiceAuthorizationBehavior>();
	var authPolicies = new List<IAuthorizationPolicy>
	{
		new ServiceAuthorizationPolicy(userValidator)
	};
	var externalAuthPolicies = new ReadOnlyCollection<IAuthorizationPolicy>(authPolicies);
	authBehavior.ExternalAuthorizationPolicies = externalAuthPolicies;
	authBehavior.PrincipalPermissionMode = PrincipalPermissionMode.Custom;

	app.UseServiceModel(builder =>
	{
		ConfigureService<CustomerService, ICustomerService> (builder);
	});
}

void ConfigureService<TService, TContract>(IServiceBuilder builder) where TService : BusinessServiceBase
																	where TContract : IBaseService
{
	builder.ConfigureServiceHostBase<TService>(host =>
	{
		host.Description.Behaviors.Remove<ServiceCredentials>();
		host.Description.Behaviors.Add(srvCredentials);
	});
	builder.AddService<TService>().AddServiceEndpoint<TService, TContract>(userPasswordBinding, string.Format("/{0}", typeof(TService).Name))
				.AddServiceEndpoint<TService, TContract>(ssoBinding, string.Format("/{0}/sso", typeof(TService).Name));
}
```

PS: I also had to add this in the server

```
services.Configure<IISServerOptions>(options =>
{
	options.AllowSynchronousIO = true;
});
```
otherwise I got an error "System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.".

**Comment by mconnew** [comment]
Because the serializers write to streams synchronously, you need to enable synchronous IO in ASP.NET Core. You can see an example of this [here](https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Http/tests/Helpers/ServiceHelper.cs#L144). Closing this issue as I believe this addresses your problem. If it doesn't, feel free to reopen.

**Comment by mconnew** [comment]
I just realized I miss read some of your issue. You are double authenticating, at the transport layer and message layer. We just identified when triaging #486 that we aren't populating the ServiceSecurityContext for transport security and Windows authentication. I believe that this should be working with message authentication. Can you try with message auth only (with TransportWithMessageCredentials) and see if your policy is populated.

**Comment by KaNarlist** [comment]
When I change the binding to message only:

```
ssoBinding = new WSHttpBinding(SecurityMode.Message);
ssoBinding.Security.Message.ClientCredentialType = MessageCredentialType.Windows;
```
I get an PlatformNotSupportedException in app.UseServiceModel(..).

This happens because of this call in WSHTTPSecurity::CreateMessageSecurity:

` return _messageSecurity.CreateSecurityBindingElement(Mode == SecurityMode.TransportWithMessageCredential, isReliableSessionEnabled, version);    `           

If the first parameter is false CreateSecurityBindingElement throws the PlatformNotSupportedException.

**Comment by KaNarlist** [comment]
If you are interested, I created a simple test solution here https://github.com/KaNarlist/WinAuthTest

**Comment by mconnew** [comment]
We don't support message security yet. You can use TransportWithMessageCredentials. It will use HTTPS to secure the communication whereas Message security encrypts the actual SOAP message itself. The practical difference in security is with full Message security you can store the raw message that's sent, eg in a SQL database, and the message can't be read except by the intended recipient. That isn't needed for 99.99% (probably more) of scenarios.

**Comment by mconnew** [comment]
I said:

> Can you try with message auth only (with TransportWithMessageCredentials) and see if your policy is populated.

`TransportWithMessageCredentials` means the secrecy and tamper detection is handled by the transport (so goes over HTTPS), but the client credentials are sent using a WS-Security security token. When you use security mode `Message`, this means the SOAP message itself is encrypted and signed. If someone were to look at the data sent to the service, they would see it's a SOAP message, but all the important parts are encrypted, and the entire message is signed. We can't support that yet due to some missing dependencies that need reimplementing.  

Our `TransportWithMessageCredentials` implementation populates the `ServiceSecurityContext` and should have all the claims populated. We can do that as we completely control the authentication mechanism. Currently our `Transport` security doesn't have integration with ASP.NET Core yet. There's no way to validate at startup whether Windows authentication has been configured in ASP.NET Core. I've only recently learnt how to trigger ASP.NET Core to initiate the authentication with the required auth scheme if the request is unauthenticated. When that integration is done, it will be a runtime failure if ASP.NET Core hasn't been configured correctly instead of a startup time failure. This is less than ideal, but it's the only option. I hope to find a way to expose the failure cause easily so that it's not a failing black box with no idea what's going wrong.  

So as of now, there's no integration into ASP.NET Core HTTP authentication to populate `ServiceSecurityContext` when using Windows auth. If you want to use `Transport` security, you will need to populate the claims from the ASP.NET Core objects yourself. If this is something that you want to do, let me know and I can give you some pointers in how to do it.

**Comment by KaNarlist** [comment]
I see. Currentley this isn't a priority for us because our client doesn't provide a way to connect your user account to your windows account and thus customers can't use it anyways. So I think it's enough for us to know, that this will probably work in the not all too distant future.

If not, I might come back to you regarding those pointers ;)

**Comment by mconnew** [comment]
Closing as no immediate need for action. Feel free to reopen if needed.
