### ISSUE TITLE
ServiceThrottlingBehavior replacement

### ISSUE THREAD

**Issue by NKnusperer** [CoreWCF/CoreWCF#547]
Hi everyone,
what is the replacement for the `System.ServiceModel.Description.ServiceThrottlingBehavior` ?
Browsing the repository I found the `CoreWCF.Dispatcher.ServiceThrottle` type which looks very promising, but I have no idea how to use it.

Btw is there also a replacement for `ServiceMetadataBehavior` and `ServiceDebugBehavior` ?

Thank you in advance :)

**Comment by mconnew** [comment]
The bones of throttling are there, but I wouldn't want to rely on it. The problem is that we're no longer in charge of the IO. For example with Net.Tcp in WCF, when we hit our concurrent pending connections limit, we would simply not call Accept again on the listening socket until a pending connection completed. A similar thing applied to HTTP. Now we're built on top of ASP.NET Core, there's a different model. We don't control pending accepts on sockets, ASP.NET Core gives them to us when they arrive. The ASP.NET Core philosophy around throttling is different than WCF's. In WCF, when you hit a throttle limit we make the client wait their turn and let the request go through once it gets to the top of the queue. This means when you are throttled, your latency goes up, but you don't reject requests (unless they timeout) when you have temporary bursts of requests. The ASP.NET Core philosophy around throttling is to respond to requests when hitting a throttle limit telling the client they have been throttled and the client needs to try again (hopefully with a backoff). There isn't currently a way to apply WCF's throttling mechanism in ASP.NET Core. I have created an issue (aspnet/aspnetcore#13295) in the asp.net core repo requesting a way to prevent new connections/requests from being handled to be able to implement the CoreWCF/WCF throttling model, but it's been on the feature backlog for a while. If you are using HTTP, then I would look into throttling solutions for asp.net core with the understanding the client will see different behavior than with WCF (rejected request needing retry instead of high latency). For NetTcp, I believe I have a way to achieve this when we take a dependency on .NET 6 (which will be for the 2.0 release). 

The ServiceMetadataBehavior and ServiceDebugBehavior feature are nearing completion. If you look at the feature/wsdl branch, you can see the current state. It's fully functional as far as I'm aware, I'm doing some code cleanup before creating a PR to have the code reviewed. It should hopefully be available in a release candidate build in the next couple of weeks.

**Comment by iyrwis** [comment]
Hi @mconnew, so for the CoreWCF based on NetTcp, do we have some ways to make it use throttling feature now?

**Comment by Kuling** [comment]
Thank you for very detailed explanation.

> The bones of throttling are there, but I wouldn't want to rely on it.

For whoever hits this place.
[I was trying](https://github.com/CoreWCF/CoreWCF/discussions/1008#discussioncomment-7156436) to use `ServiceThrottle` for limiting clients calls (property MaxConcurrentCalls).
And indeed code seems to be not fully operational yet.

For example I noticed that `ChannelHandler.RequestInfo.Cleanup` is not called at all. So as result counter of calls is never decreased. This leads to deadlock.

**Comment by cobalto** [comment]
Any update about the ServiceThrottlingBehavior or any replacement?
