### ISSUE TITLE
Mex endpoint?

### ISSUE THREAD

**Issue by schovan** [CoreWCF/CoreWCF#55]
How do I configure mex endpoint using builder.AddServiceEndpoint() method?

**Comment by wouterroos** [comment]
Hi,

I'm also wondering if this is supported. I noticed the IMetadataExchange interface is misisng from CoreWCF.

Regards,

Wouter

**Comment by mconnew** [comment]
It's not there yet as it's quite a bit of work to add and some design things are still a little in flux. I need to finalize on the channel layering API to for custom binding elements for example. For now you can generate the WSDL using .NET Framework and save the WSDL as a static file and host the static file using ASP.NET Core's static files hosting feature. I know it's not ideal, and it will come. It's a matter of time.

**Comment by mconnew** [comment]
Closing in preference of #270 which tracks multiple features that have been asked for which are provided by ServiceMetadataBehavior.

**Comment by EdgardAbud92** [comment]
Any update about this? How do I configure mex endpoint using builder.AddServiceEndpoint() method?

**Comment by LouisSimon73** [comment]
Hello @mconnew, I do not understand yet if Mex is now supported or not on CoreWcf ? We currently are migrating a soap server to .Net Core that uses Mex but clients can not be updated. Thank you in advance.

**Comment by mvarblow** [comment]
@LouisSimon73, not related to the MEX question, but if you use Windows authentication then something you should be aware of (as of 11/62023):

We have a similar situation where our clients cannot be updated. We're currently stuck (cannot roll out our new .NET 6 Core WCF server) due to #757. We opened a ticket with Microsoft Support back in April 2023. The ticket is somewhere with Microsoft engineering, but we haven't seen any movement on it. If you also use Windows auth and have .NET Framework clients that cannot be updated, then you might not want to move to CoreWCF just yet.
