### ISSUE TITLE
CustomUserNameSecurityTokenAuthenticator is internal

### ISSUE THREAD

**Issue by marlon-tucker** [CoreWCF/CoreWCF#571]
I'm in the process of converting our WCF security model over to CoreWCF and have hit a wall because `CustomUserNameSecurityTokenAuthenticator` has been marked as internal.

I'm unable to work around it by inheriting from a class further up the chain because the `UserNameSecurityToken` is also marked as internal, and that is the token type which will get created.

Is there a reason why these are marked as internal?

**Comment by ctechid** [comment]
I also have same problem. 
Look at here for [old wcf](https://github.com/dotnet/samples/tree/main/framework/wcf/Extensibility/Security).  I tried migrating the **TokenAuthenticator/CS** in **Core-WCF** but it's difficult because most classes are of internal type, so we can't be accessed that class  from outside different assemblies.

References:
https://learn.microsoft.com/en-us/dotnet/framework/wcf/samples/
https://github.com/dotnet/samples/tree/main/framework/wcf/Extensibility/Security

Thanks
Yudha

**Comment by lucashigor** [comment]
@mconnew and @birojnayak 
I Created the PR

https://github.com/CoreWCF/CoreWCF/pull/1419

**Comment by oll3ovr** [comment]
@mconnew Matt, do we know when it will be published?
