### ISSUE TITLE
Dependency Injection - unable to initialize implementation

### ISSUE THREAD

**Issue by szyb** [CoreWCF/CoreWCF#589]
I'm testing CoreWCF in version 0.4 (.NET 6) together with Dependency Injection, as the service implementation has other dependencies injected in the constructor. I was facing with the error `The service implementation object was not initialized or is not available`.
My DI setup was:
```
services.AddSingleton<ITestService, TestService>();
services.AddSingleton<ITestOtherService, TestOtherService>();
```
ITestService is an WCF Contract
The TestService implementation:
```
 public class TestService : ITestService
  {
    private readonly ITestOtherService _other;

    public TestService(ITestOtherService other)
    {
      this._other = other;
    }
```
When I changed DI setup to:
```
services.AddSingleton<TestService>();
services.AddSingleton<ITestOtherService, TestOtherService>();
```
It started work. Now I wonder, why I can't setup implementation and it's contract in DI? Is this by design?

**Comment by mconnew** [comment]
You can do what you want. CoreWCF/WCF are service type oriented. This means you create a service for a concrete implementation of a class which implements one or more interfaces. You then add endpoints to those interfaces. This is the model that was used because on .NET Framework when WCF was first created, there wasn't a built-in DI mechanism for discovery of the implementation type. If you didn't supply an instance to `ServiceHost` and only the type, it had to construct an instance using reflection. You can't construct an interface, which is why it needed a class. As CoreWCF is based on ASP.NET Core and you always have a DI mechanism available, those constraints have now been relaxed.  

There are two ways you can achieve what you want. If you want to stay with the traditional model, then you can add the concrete type to DI and make the interface type use a factory method to return the same instance. You would do that like this:
```c#
services.AddSingleton<TestService>();
services.AddSingleton<ITestService>(provider => provider.GetRequiredService<TestService>());
```
This way when CoreWCF needs an instance of the service, it gets the singleton instance of `TestService`. I presume you have other code which needs to retrieve it as `ITestService`, so when that code requests it the factory delegate gets the same `TestService` singleton instance and returns it cast as an `ITestService`.  

But that's a little messy and not ideal, I mentioned it for completeness as there might be other reasons that would be a good option for you. The easier method is to simply specify the interface as the service type. CoreWCF will then use DI to get the concrete type and use that. Your code would like something like this:
```c#
serviceBuilder.AddService<ITestService>();
serviceBuilder.AddServiceEndpoint<ITestService, ITestService>(binding, path);
```
You need to double specify the interface on `AddServiceEndpoint` as the first one specifies the service type and the second one specifies the concrete type. You could have a second service type which implements the same interface and having just the contract type would be ambiguous.  

I hope this helps. I'm going to close this issue as I believe I've answered your question. If you need more help, please reopen issue (I think you can), or at least mention me and I'll get pinged in my email.

**Comment by ismaelhamed** [comment]
I just modified the `Startup` from the `NetCoreServer` sample like this:

```
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddTransient<IAppConfig, AppConfig>();
        services.AddServiceModelServices().AddServiceModelMetadata();
    }

    public void Configure(IApplicationBuilder app)
    {
        app.UseServiceModel(builder =>
        {
            builder.AddService<IEchoService>(options => options.DebugBehavior.IncludeExceptionDetailInFaults = true)
                .AddServiceEndpoint<IEchoService, IEchoService>(new BasicHttpBinding(), "EchoService.svc");

            var serviceMetadataBehavior = app.ApplicationServices.GetRequiredService<CoreWCF.Description.ServiceMetadataBehavior>();
            serviceMetadataBehavior.HttpGetEnabled = true;
            serviceMetadataBehavior.HttpsGetEnabled = true;
        });
    }
}
```

But I'm still getting "The service implementation object was not initialized or is not available.". The `EcoService` is expecting an instance of `IAppConfig` in its ctor.

**Comment by ymauray** [comment]
I have the same exact configuration, and I get the same error : impossible to inject anything in the constructor of a Core WCF service.

**Comment by ymauray** [comment]
> But I'm still getting "The service implementation object was not initialized or is not available.". The `EcoService` is expecting an instance of `IAppConfig` in its ctor.

I had the same problem until I realized I had forgotten to add `.AddTransient<IEchoService, EchoService>()` in `ConfigureServices`.

I can now inject parameters in the constructor of `EchoService`.
