### ISSUE TITLE
Guidance on running  net core server and client

### ISSUE THREAD

**Issue by dgxhubbard** [CoreWCF/CoreWCF#64]
I copied down the zip file of src and was able to build with no problems.
I tried to run net core server and got an error 
"The project does not know how to run the profile IIS Express"
I switched the net core server project from 
Sdk="Microsoft.NET.Sdk"
to
Sdk="Microsoft.NET.Sdk.Web"
which got things started, but the browser came up for some reason with address
http://localhost:1438/
I didn't expect IIS was needed (is it) and is there some preliminary documentation to guide me through the process of running?
We are switching to .net core 3 and looking just to get our server compiling but not running until full release is available.

**Comment by mconnew** [comment]
How were you launching the .NET Core server? Did you make any changes to the project other than the Sdk change? All you should need to do is go into the src/Samples/NetCoreServer folder and run "dotnet build" followed by "dotnet run". You might need to change the TargetFramework to netcoreapp3.0 if you don't have 2.1 installed, but that's all the change you should need. It should also work if you change it to net472.

Switching to Microsoft.NET.Sdk.Web is likely to break some things as that will automatically pull in the ASP.NET Core 3.0 version (with 3.0 it now ships with .NET Core runtime and is effectively inbox) instead of running ASP.NET Core 2.1 on top of .NET Core 3.0 (treating ASP.NET Core as an external library). There are breaking changes in ASP.NET Core 3.0 and I haven't done anything to make CoreWCF work with that. The reason being that CoreWCF's initial release will run on .NET Framework with ASP.NET Core 2.1 to support a migration path and ASP.NET Core 3.0 doesn't run on .NET Framework. It's likely the v2 release will more to ASP.NET Core 3.0+.

**Comment by dgxhubbard** [comment]
I set .net core server as the startup project and hit F5. Should these just be run from the command line?

**Comment by mconnew** [comment]
You need to select NetCoreServer in this drop down of what application you want to start. I don't know why it's listing IIS Express there by default.
![image](https://user-images.githubusercontent.com/8648390/67529179-42dc1380-f670-11e9-9b49-7f7b112bbd4e.png)

**Comment by mconnew** [comment]
I found the cause and committed the fix. It was just deleting the launchSettings.json file. There were two of them, but the one causing you problems is in the NetCoreServer folder. So you can just delete that file or redownload the latest zip.
