### ISSUE TITLE
ChannelFactory implementation in CoreWCF as in System.ServiceModel

### ISSUE THREAD

**Issue by raosrip** [CoreWCF/CoreWCF#674]

**Comment by raosrip** [comment]
Currently I don't see the ChannelFactory implemented in CoreWCF which is causing issue while calling WCF service which is already using CoreWCF. Can you pls add it?

**Comment by mconnew** [comment]
This is the service side only. For the client side, you need the System.ServiceModel.XXXXX packages. That project lives at https://github.com/dotnet/wcf

**Comment by raosrip** [comment]
In my situation, I am calling another service from same service (in this case it will act as client) in server. 

How to handle this situation?

**Comment by powermetal63** [comment]
@mconnew

> This is the service side only. For the client side, you need the System.ServiceModel.XXXXX packages. That project lives at https://github.com/dotnet/wcf

This isn't clear at all. The [main page](https://github.com/CoreWCF/CoreWCF#what-is-core-wcf) say

>Core WCF is a port of Windows Communication Foundation (WCF) to .NET Core. The goal of this project is to enable existing WCF projects to move to .NET Core.

Same for the [blog post from Microsoft](https://devblogs.microsoft.com/dotnet/corewcf-v1-released/).

With all my respect for the efforts, this is misleading and gives us (who use WCF for implementing both client and server communication) a wrong impression it could help us moving from .NET Framework. Same applies for the other project you linked to, and we were not considering it as an option due to the lack of server side. Reading the announcement of your library, we though that finally we have a solution. Which according to this post is not. Using two separate implementations of a common "classic" WCF interfaces and attributes inside one and the same project is weird and virtually impossible. We are using shared dll approach, and need duplex channel over tcp and/or named pipes (we can live w/o the last), binary serializiation and  windows authentication. Both "modern" WCF replacements (gRPC and SignalR) lack some of these WCF features. Your library do have them all, hence looked very promising, but...

Anyway, it is what it is. It just would be nice to make that clear, like clearly saying in the project page the *real* intent, and that it is for server side only and that won't ever change.

**Comment by mconnew** [comment]
I've merged the update to the description to hopefully this won't be a point of confusion in the future. Closing the issue as there's nothing else left to do.
