### ISSUE TITLE
Response Aborted when Serving Files

### ISSUE THREAD

**Issue by JonathanHopeDMRC** [CoreWCF/CoreWCF#693]
Yes this is one _those_ issues.

We have a WebHttp binding using a streamed transfer mode that is used to serve files. It does so by getting a stream from blob storage and returning it from the endpoint. About 70% of the time I see an aborted error when downloading the file from that endpoint.

On the server side there is no exception, simply an info level log: the application aborted the connection. Here is a debug level log of the scenario: [aborted.log](https://github.com/CoreWCF/CoreWCF/files/8799345/aborted.log).

I cannot replicate this locally, only when the workload is deployed in the cloud. Another wrinkle is that the call always succeeds when I run it from my desktop which is wired to the network. I can only replicate the issue making calls to the service hosted in the cloud from my laptop which is wireless.

I recognize that this is a very specific scenario with very little to go off of. The same endpoint did work correctly in old WCF.

**Comment by mconnew** [comment]
I had a look at the code. I initially thought the issue might be that the HttpContext was disposed before we finished writing, but that doesn't look to be the case. My best guess is that XmlByteStreamWriter doesn't implement FlushAsync, and the implementation will fall back to XmlWriter.FlushAsync which will throw a NotImplementedException. ByteStreamMessageEncoder.WriteMessageAsync has this code:
```c#
            using (XmlWriter writer = new XmlByteStreamWriter(stream, false))
            {
                await message.WriteMessageAsync(writer);
                await writer.FlushAsync();
            }
```
This doesn't interact well with HttpOutput.WriteStreamedMessageAsync calls GetWrappedOutputStream which wraps the output stream with a BufferedStream. This has the effect that the last write to the output stream might be buffered. The FlushAsync above is supposed to cause the final write to be sent, but instead it's throwing. If this isn't your problem, it's still a problem. The fix for this problem is to implement the FlushAsync method on XmlByteStreamWriter like this:
```c#
        public override Task FlushAsync()
        {
            ThrowIfClosed();
            return _stream.FlushAsync();
        }
```

**Comment by JonathanHopeDMRC** [comment]
Wow OK I have no idea how you figured that out, but yes that works. PR is here: https://github.com/CoreWCF/CoreWCF/pull/694

**Comment by mconnew** [comment]
You know how they say one of the worst ways to debug code is to stare at it, I think I missed that lesson in college and got really good at executing code in my head and finding obscure bugs that way 😁

**Comment by mconnew** [comment]
Closing as fix was merged
