### ISSUE TITLE
Can CoreWCF.ConfigurationManager fully support configuring services using a configuration file?

### ISSUE THREAD

**Issue by WenningQiu** [CoreWCF/CoreWCF#706]
The existing CoreWCF.ConfigurationManager (1.0.2) supports loading service and endpoint configuration from a configuration file, however it still require some configuration work to be done in the code. The in-code configuration sometimes has to contain the type information that is in the configuration file, which creates undesirable coupling that defeats the purpose of using a configuration file (see details below for examples), in other times it has to provide information that is not supported by the configuration file.  

Such gap is blocking the effort of converting our custom generic ServiceHost+ServiceHostFactory that solely use configuration files for service configuration. So it is desirable that CoreWCF.ConfigurationManager can fully support configuring services and endpoints in a configuration file. 

I list below a few scenarios that I have run into :

1. When I need to call IServiceBuilder.ConfigureServiceHostBase to customize services defined in the configuration file, I have to provide the service type in the code. It would eliminate the service type coupling in the code if the services loaded from a configuration file had been exposed in IServiceBuilder.Services property (or via a new property); in my observation, IServiceBuilder.Services currently only contain services added by IServiceBuilder.AddService().

2. We seem to be lacking a way to automatically configure Kestrel based on the service endpoint address information, applications will have to come up with its own way of acquiring the binding and port information for Kestrel configuration. It would be great if CoreWCF.ConfigurationManager can provide extension methods that configure Kestrel based on information in <system.serviceModel> section.

3. It appears that the only way we can set up metadata endpoints is in the code with the existing implementation (1.0.2). It would be ideal that CoreWCF.ConfigurationManager can support configuring metadata endpoints in the configuration file.

**Comment by mconnew** [comment]
I see a few possible tasks for investigating leading from your questions:  
1. An open ended ConfigureServiceHostBase which executes for all services. You would need to discover the service type by checking the ServiceHostBase instance.  
2. Make the configuration be loaded before running the UseServiceModel delegate.
3. Create a configuration provider mechanism for configuring CoreWCF, where one of the components would be port configuration so that we can automatically configure NetTcp/Http listening ports.

One possible solution for your first question is to inject an IServiceBehavior into DI which will get applied to every service automatically without you having to specify the service type. There's lots of things an IServiceBehavior can do that might be sufficient for your needs.  

For your second question, Kestrel is only one Http Server implementation. The code should be agnostic of the Http server type being used. I think we can do a bit more around using configuration providers for NetTcp and Http and creating one which reads the base addresses in the WCF configuration file. We could then have UseNetTcp find it's port number(s) this way, and that would also drive any other Http server implementations which can read from a configuration provider. I'm worried about a chicken and egg situation where we might not have the info we need yet. It's worth investigating to see what can be done.  

For your third problem, we are lacking behavior configuration completely. When the configuration support was being written, the developer said that it was a significant task to add that which is why it wasn't in the initial release. We're open to contributions around that. It's definitely a known gap in the configuration story. This is being tracked in #446
