### ISSUE TITLE
OperationContract with CultureInfo parameter

### ISSUE THREAD

**Issue by HoHoPl** [CoreWCF/CoreWCF#791]
I'm having issues when I try to use CultureInfo as parameter in OperationContract during generation of wsdl and serialization/deserialization. Unfortunatelly I can't change this parameter to string because it's used in existing implementation and I can't change existing contracts - we're just trying to move them to .net core.

`System.Runtime.Serialization.InvalidDataContractException: Type 'System.Globalization.CultureData' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. Alternatively, you can ensure that the type is public and has a parameterless constructor - all public members of the type will then be serialized, and no attributes will be required.`

In .Net Framework it was enough to use below section in app.config.

```
<system.runtime.serialization>
    <dataContractSerializer>
      <declaredTypes>
        <add type="System.Globalization.CultureInfo, mscorlib,Version=2.0.0.0, Culture = neutral, PublicKeyToken=b77a5c561934e089">
          <knownType type="System.Globalization.GregorianCalendar,mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
        </add>
      </declaredTypes>
    </dataContractSerializer>
  </system.runtime.serialization>
```
  
 Is there any workaround for this issue in CoreWcf?

**Comment by mconnew** [comment]
The cause of your problem is the .NET Runtime no longer has the `[Serializable]` attribute applied to CultureInfo and transitive classes such as NumberFormatInfo. The only solution which might work at all is to use a data contract serializer surrogate provider. This enables you to create your own type which serializes to the same XML as you are expecting, and then in the surrogate provider you create an instance of your type based on the CultureInfo instance. This was reported [in this issue](https://github.com/dotnet/standard/issues/1624) in a dotnet repo for the NumerFormatInfo type and that was their suggestion. I'm not sure if the surrogate provider api's are public yet on CoreWCF, but you can still work on the surrogate provider using DataContractSerializer directly. Let us know if that's the route you are going to take.
