### ISSUE TITLE
AddServiceWebEndpoint and "" address returns 404

### ISSUE THREAD

**Issue by mevsie** [CoreWCF/CoreWCF#892]
Our existing REST WCF service doesn't have a sub folder on its hosted url - i.e. it's just http://myserver:1234 not http://myserver:1234/api. 

Specifying a blank address works ok when dealing with AddServiceEndpoint with BasicHttpBinding, but not with AddServiceWebEndpoint and WebHttpBinding. 404 is always returned unless a non blank address is specified. You can reproduce this by modifying the WebHttp sample project and changing "api" to "" in the addservicewebendpoint calls in startup. 

I've tried "./" etc. It's possibly something I'm missing, any help appreciated.

Cheers

Mark

**Comment by arontsang** [comment]
You can work around this by using an absolute Uri, for example `$"http://{Environment.MachineName}:1234"

The issue seems to be a bug in `ServiceHost.MakeAbsoluteUri` or possibly in `PathString.StartsWithSegment` can't decide which.

"/foo/bar".StartsWithSegment("/foo/", out _ , out _) will return false.

So a change needs to be made to `ServiceHost.MakeAbsoluteUri` to allow the output to match.

**Comment by mevsie** [comment]
Thanks for looking into this.

No luck with the workaround - I assume you meant to add the absolute uri as the address parameter to AddServiceWebEndpoint - gave that a try as a string and as a uri constructed to be absolute. 

Also tried hardcoding machine names in UseUrls/Kestrel Endpoints

**Comment by arontsang** [comment]
@mevsie  is in
 Feel free to push the Devs to merge
