### ISSUE TITLE
CoreWcf nuget package transition

### ISSUE THREAD

**Issue by benmccallum** [CoreWCF/CoreWCF#9]
**Tasks**
1. Let me know who the owners need to be and we can start the transition. 
2. Would be nice to have a footnote on the readme of this repo that mentions and links back to my repo just so that if someone did get confused and lost they'd know where to go. 
2.1 I'll do same from my old repo to this one.
3. De-list the existing versions once the first release from here is made?

**Comment by mikeasage** [comment]
So, how do we want this to be setup?  Separate packages for CoreWCF.Http, CoreWcf.NetTcp and CoreWCF.Primitives?  

There also is that shared folder with CoreWCF code which looks to be compiled into the .Http dll, .NetTcp dll, and the Primitives dll, unless I am missing something.  Should that maybe only be compiled into Primitives?

**Comment by mconnew** [comment]
@mikeasage, one problem we have with the implementation on .NET Framework is that because everything is shoved into one big assembly (well, 2 if you count System.ServiceModel.Internals but there's a friend relationship which effectively makes it one assembly split in two for practical purposes), many abstractions aren't clean and code "peeks" into or calls across abstraction boundaries that it shouldn't. This has two negative effects. 1. Sometimes behaviors can't be modified by application code because the necessary pieces aren't exposed. 2. Some bugs/problems can be really difficult to analyze because code is calling into places it shouldn't and class interactions can be tough to untangle, also making fixes harder.  
So I decided to make everything so that an external concrete implementation of any components such as a custom transport was able to be as capable as an "inbox" component. One example on .Net Framework was the fact that the interface `IChannelBindingProvider` is internal only, you couldn't fully replace `SslStreamSecurityBindingElement` as an out of box implementation is unable to support `ChannelBinding`. Having separate packages keeps us honest with api boundaries. One example where I've exposed something new already is in AddressingVersion. I've exposed `NoneUri` and `AnonymousUri` as they are needed by the various transports.    
So then we come to the common shared folder. There's some internal boiler plate code that does need to be used in each assembly. Making it public in Primitives makes it a public API which can't be changed as it's inevitable that people will start using them regardless of any warnings and then get upset when you break them. We should definitely try and keep this set to a minimum so as to reduce the memory usage. If you see a shared type which is a good candidate for making public or can be eliminated, feel free to open an issue.

**Comment by tibor19** [comment]
@mikeasage My preference would be to have separate packages (CoreWCF.Http, CoreWcf.NetTcp and CoreWCF.Primitives) and to use CoreWCF as metapackage. The alternative would be to use CoreWCF as "host" for CoreWCF.Primitives, and one package per binding.

**Comment by mconnew** [comment]
@benmccallum, we could use the name CoreWCF.All as a metapackage name and not push yours out of the way. It might be enough to simply add a note to your description pointing to CoreWCF.All.

**Comment by benmccallum** [comment]
I'm not fussed either way. I'd suggest CoreWCF.All if you wanted to start from v1, else use mine but you'll have to start from v2.

**Comment by dotnetchris** [comment]
My recommendation would be to consolidate Primitives & Tcp into CoreWCF and then satellite projects for Http, etc.

Really should do everything possible to discourage http use and set up the pit of success with real service communication.

Related, could also consider renaming the project to .NET Communication Framework/NCF or Service Communication Framework/SCF given that "Core" doesn't even exist long term and it will only be .NET5

Or even just "SOA", the 'SOA' package name is directly taken on nuget.org by a package abandoned in 2016. Could possibly be taken ala cyber squatting just like a person publishing a Coke or Pepsi package could have it removed.

**Comment by Treit** [comment]
> My recommendation would be to consolidate Primitives & Tcp into CoreWCF and then satellite projects for Http, etc.
> 
> Really should do everything possible to discourage http use and set up the pit of success with real service communication.

Pretty sure SOAP over HTTP is one of the primary motivations for this project existing at all.

**Comment by tibor19** [comment]
CoreWCF package is de-listed. @benmccallum is still the owner, but once the package is not used anymore, the ownership will be transferred to the CorewCF organisation.
