### ISSUE TITLE
How-to use CoreWCF for call Web Service ?

### ISSUE THREAD

**Issue by kiquenet** [CoreWCF/CoreWCF#931]
I need to call Web Service (SOAP) from my NET 6 app (Blazor), really from my "Library".

Using CoreWCF ?

**Comment by mconnew** [comment]
The WCF client code lives in https://github.com/dotnet/wcf. It's not going to work in the blazor web assembly because of at least one bug in the runtime preventing it. You should be able to use it with blazor server when the WCF client instance is instantiated on dotnet runtime and not in the browser. Any followup questions should be directed to the dotnet/wcf repo so closing this issue.
