### ISSUE TITLE
Where can I find WSDL?

### ISSUE THREAD

**Issue by NikErmRnd** [CoreWCF/CoreWCF#95]
What is the link to this file for example?

**Comment by ISTAnsver** [comment]
I also need WSDL. May somebody answer the question please?

**Comment by SergeySukhov** [comment]
Same problem
Importing project to net core, client sends GET request for wsdl file and then throw the exception

**Comment by mconnew** [comment]
WSDL isn't going to be in the initial release because there is a workaround, although admittedly annoying. You can host the WSDL files as static files for now, and generate the WSDL using .NET Framework. The reason for not having it in the initial release is to get a stable code base for running services so this can be used sooner.  
My current thinking for WSDL is to make it more flexible than the current system in WCF. In WCF the WSDL is created at runtime which means if you want to modify the WSDL at all, you need to hook into the extensibility points for WSDL creation, and those api's aren't super friendly. I plan to have the code which generates the WSDL run outside of the the WCF service context. It will be runnable in two ways, either as middleware in ASP.NET Core and have it reflect into CoreWCF's contract description and generate the WSDL, or optionally have it be a design time tool where it can generate most of the WSDL at build time and output the xsd files to be statically hosted. There will still need to be a runtime component to generate the port bindings and profiles as discovering them at build time isn't feasible, but the contract part can be done ahead of time. This makes it easier to modify the wsdl as you can do things like use XSLT to modify it.

**Comment by danielmeza** [comment]
@mconnew do you have thinking about OpenApi? And nswag generator?

**Comment by mconnew** [comment]
@danielmeza, from the [OpenApi spec](http://spec.openapis.org/oas/v3.0.3), it says:

> The OpenAPI Specification (OAS) defines a standard, programming language-agnostic interface description for REST APIs

I'm not targeting REST as running CoreWCF on top of ASP.NET Core which includes WebAPI to then dispatch to a second REST API mechanism as that seems less than ideal. So OpenApi isn't relevant to non-REST stacks.

From the NSwag project README it says:

> The OpenAPI/Swagger specification uses JSON and JSON Schema to describe a RESTful web API. 

So again, Swagger isn't really applicable.

**Comment by mconnew** [comment]
Closing in preference of #270 which tracks multiple features that have been asked for which are provided by ServiceMetadataBehavior.
