### ISSUE TITLE
Duplicate variables when generated code with Web References

### ISSUE THREAD

**Issue by Sakchai** [CoreWCF/CoreWCF#971]
Hi CoreWCF Team,

I used VB Application and add Web Reference with CoreWCF http://localhost:5000/CalculatorService/basicHttp?singleWsdl

From your example
```
namespace CoreWcf.Samples.Http
{
    // Define a service contract.
    [ServiceContract]
    public interface ICalculatorService
    {
        [OperationContract]
        double Add(double n1, double n2);
        [OperationContract]
        double Subtract(double n1, double n2);
        [OperationContract]
        double Multiply(double n1, double n2);
        [OperationContract]
        double Divide(double n1, double n2);
        [OperationContract]
        string wsVOGetDirectReferrals(string prmTCO);
    }
}

```
I generated code with Web References from  http://localhost:5000/CalculatorService/basicHttp?singleWsdl. But there are **ByVal n1Specified As Boolean**,  **ByVal n2Specified As Boolean** and **ByVal userState As Object** in Reference.vb

```
        Public Overloads Sub AddAsync(ByVal n1 As Double, ByVal n1Specified As Boolean, ByVal n2 As Double, ByVal n2Specified As Boolean, ByVal userState As Object)
            If (Me.AddOperationCompleted Is Nothing) Then
                Me.AddOperationCompleted = AddressOf Me.OnAddOperationCompleted
            End If
            Me.InvokeAsync("Add", New Object() {n1, n1Specified, n2, n2Specified}, Me.AddOperationCompleted, userState)
        End Sub
```

How I get rid **Specified As Boolean** and **ByVal userState As Object**  when generated code with Web References.
        
 Thank you.

**Comment by mconnew** [comment]
This is how the old Web Reference implementation generated async code as async/await with Task's didn't exist when that tool was created. Calling the generated AddAsync will return as soon as the request has been sent. When the result comes back, it will call the registered event handler OnAddOperationCompleted passing your userState object to that event handler. This allows you to tell one callback apart from another, by allowing you to provide some state info. The userState isn't passed to the service, it's just used for the local async completion callback mechanism.  

I'm not sure about the Specified values, but at a guess I suspect it's because double's are value types so aren't nullable, but at the XML level, they can be optional. I suspect it's used to tell the client code whether a value of 0.0 should be sent. I think this is using the WebReference SoapClient on .NET Framework. If this isn't being generated from an equivalent service on .NET Framework, we might have a bug in the wsdl generation stating these are nillable values causing this to be generated.  

You have a few options. You can pass null as userState and true for the specified arguments. Or you can switch to the "Add Service Reference" implementation (Add Web Reference is the old .NET 2.0 Web Services client generation tool, and Add Service Reference is the WCF tool) which doesn't generate code like this.

**Comment by Sakchai** [comment]
I found that if there are wsdl from the old .NET Web Services it generates correctly. but when I used CoreWCF if there are variables such as double , int, DateTime, decimal  the old .NET Web Services it generates wrong.
