### ISSUE TITLE
CoreWCF 1.2+ is not compatible with Microsoft.AspNetCore.Authentication.Negotiate on .NET 6.0

### ISSUE THREAD

**Issue by mvarblow** [CoreWCF/CoreWCF#998]
It's been hard to find clear documentation on what configurations are supported and how they should be configured in code. But it _seems_ that Windows authentication has been supported by CoreWCF for a while now via ASP.NET Core authentication middleware.

However, as far as I can tell, it's been broken since CoreWCF 1.2.0 for projects targeting .NET 6. For a very simple repro:

1. Create a new CoreWCF project from the template, target .NET 6.0.

2. Add the following package reference:

    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="6.0.13" />

3. Add Windows authentication services:

builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate();

4. Run the project. It'll blow up immediately during startup:

```
Could not load file or assembly 'System.DirectoryServices.Protocols, Version=6.0.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at Microsoft.AspNetCore.Authentication.Negotiate.PostConfigureNegotiateOptions.PostConfigure(String name, NegotiateOptions options) in /_/src/Security/Authentication/Negotiate/src/PostConfigureNegotiateOptions.cs:line 94
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name) in /_/src/libraries/Microsoft.Extensions.Options/src/OptionsFactory.cs:line 67

```

If I change the project to specifically target CoreWCF 1.1.1 (or earlier) then it starts up just fine. Also, if I change the Microsoft.AspNetCore.Authentication.Negotiate package reference to 6.0.0 or 6.0.1 then it also starts up just fine. It looks like since 6.0.2, Microsoft.AspNetCore.Authentication.Negotiate has required System.DirectoryServices.Protocols >= 6.0.1 && < 7.0.0?
I expect that Microsoft.AspNetCore.Authentication.Negotiate 7.0.0 doesn't have this problem but it is not compatible with .NET 6.0.

This seems to block the use of Microsoft.AspNetCore.Authentication.Negotiate (with recent patches) with CoreWCF 1.2+ on .NET 6.0.

**Comment by mconnew** [comment]
You should be able to override the System.DirectoryServices.Protocols version by adding a direct dependency to your app. This enables you to force downgrading to 6.0.x. We don't have any api dependencies on the latest version so I wouldn't expect this to break anything.  
The cause of this problem is a bug in either System.DirectoryServices.Protocols or Microsoft.AspNetCore.Authentication.Negotiate as they should be compatible with each other. This problem would happen with any netstandard library which has a dependency on System.DirectoryServices.Protocols 7.0.0. I suggest opening an issue in the dotnet/aspnet repo for the underlying incompatibility to be fixed.

**Comment by mvarblow** [comment]
> You should be able to override the System.DirectoryServices.Protocols version by adding a direct dependency to your app. This enables you to force downgrading to 6.0.x. 

The nuget package manager fails to restore the packages if I do this. For example:

```
    <PackageReference Include="CoreWCF.Primitives" Version="1.3.1" />
    <PackageReference Include="CoreWCF.Http" Version="1.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="6.0.14" />
    <PackageReference Include="System.DirectoryServices.Protocols" Version="6.0.1" />
```

This fails to build/restore with an error similar to:
```
MyProject.csproj : error NU1605: Detected package downgrade: System.DirectoryServices.Protocols from 7.0.0 to 6.0.1. Reference the package directly from the project to select a different version.
MyProject.csproj : error NU1605:  Configuration.Service -> CoreWCF.Primitives 1.3.1 -> System.DirectoryServices.Protocols (>= 7.0.0)
MyProject.csproj : error NU1605:  Configuration.Service -> System.DirectoryServices.Protocols (>= 6.0.1)
```

> We don't have any api dependencies on the latest version so I wouldn't expect this to break anything.

In this case, couldn't CoreWCF reference a lower version to maintain broader compatibility? 

The only way I've been able to reference the latest CoreWCF with Microsoft.AspNetCore.Authentication.Negotiate (with .NET 6) has been to target the Negotiate 6.0.1 package. But this seems problematic from a security perspective.

**Comment by mvarblow** [comment]
I filed a bug with aspnetcore. 

https://github.com/dotnet/aspnetcore/issues/47248

However, I still think it would be helpful if CoreWCF took the lower dependency for System.DirectoryServices and System.DirectoryServices.Protocols -- like it does with Microsoft.AspNetCore and so many others -- to make it compatible with .NET 6 now.

**Comment by Tratcher** [comment]
@mconnew CoreWCF.Primitives dependencies are all over the place. AspNetCore and Extensions 2.1, DirectoryServices 7, Cryptography 6, Principal 5, etc.

This package should add a separate dependency list for major TFMs so the dependencies align as expected.

**Comment by Tratcher** [comment]
> #### AspNetCore and Extensions 2.1
> These are the latest supported versions that run on .NET Framework. Those shouldn't be a problem as I understand there's some redirection logic to use the inbox versions at runtime. If that mechanism is deprecated, please let me know.

What are you consuming from these? By using the 2.1 packages, you're limiting Core apps to the 2.1 APIs even if there is binary unification. I'd recommend adding at least a 3.1 TFM that switches to the shared framework reference. Netstandard is no longer viable as a way to reference AspNetCore on .NET Core 3.1+, it's a dead end.

**Comment by Tratcher** [comment]
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-7.0&tabs=visual-studio#use-the-aspnet-core-shared-framework

**Comment by mconnew** [comment]
Our unit tests all use the FrameworkReference for non-Framework test runs. There's only a few things we actually need from asp.net core in our Primitives package. We use HttpContext and it's various properties, we use the IApplicationBuilder extension methods Map and MapWhen to hook in as middleware. We use one of the IApplicationLifetime interfaces to hook into the app to clean things up when the app is being stopped. We also use IServerAddressesFeature and the IServer interface.  
For NetTcp, we use the IConnectionBuilder interface and some extension methods, ConnectionContext with the connection builder.  

Anyone consuming CoreWCF is expected to use FrameworkReference to pull in asp.net core (or use the .Web sdk which does the same thing).  

The particular problem being hit could happen even if we multi-targeted. DirectoryServices.Protocols explicitly supports .NET 6.0 in the 7.0 package so any app could pull in something which depends on 7.0 while running on .NET 6.0. Trying to change the library which depends on DirectoryServices.Protocols 7.0 instead of fixing the underlying problem is playing wack-a-mole.  It also sets a really bad precedent that when a Microsoft owned library which explicitly declares it supports a .NET version but has a breaking bug preventing it, that the expectation isn't to fix the broken library but instead consumers should change what they are consuming.  
If DirectoryServices.Protocols 7.0 isn't expected to work on .NET 6.0, it shouldn't explicitly declare support:
![image](https://user-images.githubusercontent.com/8648390/226486633-c01eefdf-3c3e-4156-9525-2f9ca18ca0ce.png)

**Comment by mconnew** [comment]
I learnt the root cause of the problem. The System.DirectoryServices.Protocols package implements classes which exist on .NET Framework. If you have a library which targets netstandard2.0, it needs to run on .NET Framework. In this case, it needs to cause the app to use the in-box framework version. The only way this works is if the version of the assembly is 4.0.0.0 to match the .NET Framework version. If it was a higher version, then the assembly resolver in .NET Framework would reject in the in-box version as the version number would be too low.  

There was a bug in the servicing mechanism for the .NET runtime. The 6.0.0 version of the package correctly had 4.0.0.0 as the assembly version. When a servicing release was done for .NET 6.0.1, the assembly version was incorrectly updated to 6.0.0.1. When the asp.net core library was recompiled as part of the servicing release, it was compiled referencing System.DirectoryServices.Protocols assembly version 6.0.0.1. When CoreWCF pulled in the 7.0 version of the library, that has the correct 4.0.0.0 assembly version. But this can't be loaded by asp.net core as it expects an assembly version of 6.0.0.1.

Below you can see a screenshot of the nuget packages for 6.0.0, 6.0.1, and 7.0.0 with their assembly versions.

![image](https://user-images.githubusercontent.com/8648390/229210824-e0d48b1b-a423-44da-9f8a-66b4aa6e9922.png)

**Comment by stcpottdav** [comment]
1.3.2 works now if System.DirectoryServices.Protocols 7.01 is added as a package reference.

**Comment by mvarblow** [comment]
The CoreWCF 1.4.1 package seems to work fine. No need to add an explicit System.DirectoryServices.Protocols package reference.
